<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'id_fk',
'Username',
'Password',
'usr_email',
'usr_name',
'usr_lname',
'usr_nombresfull',
'usr_personalid',
'usr_inicial',
'usr_sessini',
'usr_image',
'usr_status_nomina',
'usr_status',
'usr_rdnkey',
'usr_type_vinc',
'usr_type_vinculacion',
'usr_status_sol',
'usr_dependencia',
'user_dep',
'usr_entidad',
'usr_not',
'usr_not_msj',
'usr_jefe',
'usr_minequipo_lider',
'usr_minequipo_grupo',
'global_rol_me',
'global_rol_gh',
'global_rol_almacen',
'global_rol_ci',
'global_rol_contratos',
'global_rol_hojar',
'global_rol_inmuebles',
'global_rol_siis',
'global_rol_cpanel',
'global_rol_dashboard',
'global_rol_zf',
'global_rol_sipi',
'global_rol_cej',
'global_rol_jc3',
'global_rol_th',
'global_rol_sid',
'global_rol',
'global_rol_cont',
'globla_rol_ct',
'global_rol_procjur',
'global_rol_comacc',
'global_rol_gestion',
'global_rol_ciudadano',
'global_rol_ciudadano_dep',
'sys_user',
'sys_date',
'sys_time',
'sys_ntries_usr',
'sys_registrationdate_usr',
'sys_expiration_usr',
'sys_disabledate_usr',
'sys_upd_fecha',
'sys_upd_user',
'sys_upd_time',
'sys_update_info',
'sys_update_family_info',
'usr_update_almacen',
'sys_anio',
'ctrl',
'usr_directivo',
'usr_dep',
'usr_dep_sup',
'usr_cargo',
'usr_regpago',
'usr_extension',
'usr_piso',
'usr_datebirth',
'ctrl_pedidoalmacen',
'ctrl_contacto',
'usr_emergencia',
'active',
'groupid',
'habilita_almacen',
'estado_vinculacion_mincit',
'upd_date',
'phone',
'phone1' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'id_fk' => array( 'integrated_edit_field' ),
'Username' => array( 'integrated_edit_field1' ),
'Password' => array( 'integrated_edit_field2' ),
'usr_email' => array( 'integrated_edit_field3' ),
'usr_name' => array( 'integrated_edit_field4' ),
'usr_lname' => array( 'integrated_edit_field5' ),
'usr_nombresfull' => array( 'integrated_edit_field6' ),
'usr_personalid' => array( 'integrated_edit_field7' ),
'usr_inicial' => array( 'integrated_edit_field8' ),
'usr_sessini' => array( 'integrated_edit_field9' ),
'usr_image' => array( 'integrated_edit_field10' ),
'usr_status_nomina' => array( 'integrated_edit_field11' ),
'usr_status' => array( 'integrated_edit_field12' ),
'usr_rdnkey' => array( 'integrated_edit_field13' ),
'usr_type_vinc' => array( 'integrated_edit_field14' ),
'usr_type_vinculacion' => array( 'integrated_edit_field15' ),
'usr_status_sol' => array( 'integrated_edit_field16' ),
'usr_dependencia' => array( 'integrated_edit_field17' ),
'user_dep' => array( 'integrated_edit_field18' ),
'usr_entidad' => array( 'integrated_edit_field19' ),
'usr_not' => array( 'integrated_edit_field20' ),
'usr_not_msj' => array( 'integrated_edit_field21' ),
'usr_jefe' => array( 'integrated_edit_field22' ),
'usr_minequipo_lider' => array( 'integrated_edit_field23' ),
'usr_minequipo_grupo' => array( 'integrated_edit_field24' ),
'global_rol_me' => array( 'integrated_edit_field25' ),
'global_rol_gh' => array( 'integrated_edit_field26' ),
'global_rol_almacen' => array( 'integrated_edit_field27' ),
'global_rol_ci' => array( 'integrated_edit_field28' ),
'global_rol_contratos' => array( 'integrated_edit_field29' ),
'global_rol_hojar' => array( 'integrated_edit_field30' ),
'global_rol_inmuebles' => array( 'integrated_edit_field31' ),
'global_rol_siis' => array( 'integrated_edit_field32' ),
'global_rol_cpanel' => array( 'integrated_edit_field33' ),
'global_rol_dashboard' => array( 'integrated_edit_field34' ),
'global_rol_zf' => array( 'integrated_edit_field35' ),
'global_rol_sipi' => array( 'integrated_edit_field36' ),
'global_rol_cej' => array( 'integrated_edit_field37' ),
'global_rol_jc3' => array( 'integrated_edit_field38' ),
'global_rol_th' => array( 'integrated_edit_field39' ),
'global_rol_sid' => array( 'integrated_edit_field40' ),
'global_rol' => array( 'integrated_edit_field41' ),
'global_rol_cont' => array( 'integrated_edit_field42' ),
'globla_rol_ct' => array( 'integrated_edit_field43' ),
'global_rol_procjur' => array( 'integrated_edit_field44' ),
'global_rol_comacc' => array( 'integrated_edit_field45' ),
'global_rol_gestion' => array( 'integrated_edit_field46' ),
'global_rol_ciudadano' => array( 'integrated_edit_field47' ),
'global_rol_ciudadano_dep' => array( 'integrated_edit_field48' ),
'sys_user' => array( 'integrated_edit_field49' ),
'sys_date' => array( 'integrated_edit_field50' ),
'sys_time' => array( 'integrated_edit_field51' ),
'sys_ntries_usr' => array( 'integrated_edit_field52' ),
'sys_registrationdate_usr' => array( 'integrated_edit_field53' ),
'sys_expiration_usr' => array( 'integrated_edit_field54' ),
'sys_disabledate_usr' => array( 'integrated_edit_field55' ),
'sys_upd_fecha' => array( 'integrated_edit_field56' ),
'sys_upd_user' => array( 'integrated_edit_field57' ),
'sys_upd_time' => array( 'integrated_edit_field58' ),
'sys_update_info' => array( 'integrated_edit_field59' ),
'sys_update_family_info' => array( 'integrated_edit_field60' ),
'usr_update_almacen' => array( 'integrated_edit_field61' ),
'sys_anio' => array( 'integrated_edit_field62' ),
'ctrl' => array( 'integrated_edit_field63' ),
'usr_directivo' => array( 'integrated_edit_field64' ),
'usr_dep' => array( 'integrated_edit_field65' ),
'usr_dep_sup' => array( 'integrated_edit_field66' ),
'usr_cargo' => array( 'integrated_edit_field67' ),
'usr_regpago' => array( 'integrated_edit_field68' ),
'usr_extension' => array( 'integrated_edit_field69' ),
'usr_piso' => array( 'integrated_edit_field70' ),
'usr_datebirth' => array( 'integrated_edit_field71' ),
'ctrl_pedidoalmacen' => array( 'integrated_edit_field72' ),
'ctrl_contacto' => array( 'integrated_edit_field73' ),
'usr_emergencia' => array( 'integrated_edit_field74' ),
'active' => array( 'integrated_edit_field75' ),
'groupid' => array( 'integrated_edit_field76' ),
'habilita_almacen' => array( 'integrated_edit_field77' ),
'estado_vinculacion_mincit' => array( 'integrated_edit_field78' ),
'upd_date' => array( 'integrated_edit_field79' ),
'phone' => array( 'integrated_edit_field80' ),
'phone1' => array( 'integrated_edit_field81' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field34' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field52' => 'grid',
'integrated_edit_field53' => 'grid',
'integrated_edit_field54' => 'grid',
'integrated_edit_field55' => 'grid',
'integrated_edit_field56' => 'grid',
'integrated_edit_field57' => 'grid',
'integrated_edit_field58' => 'grid',
'integrated_edit_field59' => 'grid',
'integrated_edit_field60' => 'grid',
'integrated_edit_field61' => 'grid',
'integrated_edit_field62' => 'grid',
'integrated_edit_field63' => 'grid',
'integrated_edit_field64' => 'grid',
'integrated_edit_field65' => 'grid',
'integrated_edit_field66' => 'grid',
'integrated_edit_field67' => 'grid',
'integrated_edit_field68' => 'grid',
'integrated_edit_field69' => 'grid',
'integrated_edit_field70' => 'grid',
'integrated_edit_field71' => 'grid',
'integrated_edit_field72' => 'grid',
'integrated_edit_field73' => 'grid',
'integrated_edit_field74' => 'grid',
'integrated_edit_field75' => 'grid',
'integrated_edit_field76' => 'grid',
'integrated_edit_field77' => 'grid',
'integrated_edit_field78' => 'grid',
'integrated_edit_field79' => 'grid',
'integrated_edit_field80' => 'grid',
'integrated_edit_field81' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field' => array( 'field' => 'id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'Username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'Password',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'usr_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'usr_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'usr_lname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'usr_nombresfull',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'usr_personalid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'usr_inicial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'usr_sessini',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'usr_image',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'usr_status_nomina',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'usr_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'usr_rdnkey',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'usr_type_vinc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'usr_type_vinculacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'usr_status_sol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'usr_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'user_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'usr_entidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'usr_not',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'usr_not_msj',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'usr_jefe',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'usr_minequipo_lider',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'usr_minequipo_grupo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'global_rol_me',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'global_rol_gh',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'global_rol_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'global_rol_ci',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'global_rol_contratos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'global_rol_hojar',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'global_rol_inmuebles',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'global_rol_siis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'global_rol_cpanel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'global_rol_dashboard',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'global_rol_zf',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'global_rol_sipi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'global_rol_cej',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'global_rol_jc3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'global_rol_th',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'global_rol_sid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'global_rol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'global_rol_cont',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'globla_rol_ct',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'global_rol_procjur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'global_rol_comacc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'global_rol_gestion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'global_rol_ciudadano',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'global_rol_ciudadano_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'sys_time',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'sys_ntries_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field53' => array( 'field' => 'sys_registrationdate_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field54' => array( 'field' => 'sys_expiration_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'sys_disabledate_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field56' => array( 'field' => 'sys_upd_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field57' => array( 'field' => 'sys_upd_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field58' => array( 'field' => 'sys_upd_time',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field59' => array( 'field' => 'sys_update_info',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'sys_update_family_info',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field61' => array( 'field' => 'usr_update_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field62' => array( 'field' => 'sys_anio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field63' => array( 'field' => 'ctrl',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field64' => array( 'field' => 'usr_directivo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field65' => array( 'field' => 'usr_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field66' => array( 'field' => 'usr_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field67' => array( 'field' => 'usr_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field68' => array( 'field' => 'usr_regpago',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field69' => array( 'field' => 'usr_extension',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field70' => array( 'field' => 'usr_piso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field71' => array( 'field' => 'usr_datebirth',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field72' => array( 'field' => 'ctrl_pedidoalmacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field73' => array( 'field' => 'ctrl_contacto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'usr_emergencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'active',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field76' => array( 'field' => 'groupid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field77' => array( 'field' => 'habilita_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field78' => array( 'field' => 'estado_vinculacion_mincit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field79' => array( 'field' => 'upd_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field80' => array( 'field' => 'phone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field81' => array( 'field' => 'phone1',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>