<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'OP_ID' => array( 'totalsType' => '' ),
'Numero Documento' => array( 'totalsType' => '' ),
'Fecha de Registro' => array( 'totalsType' => '' ),
'Fecha de pago' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'Valor Bruto' => array( 'totalsType' => '' ),
'Valor Deducciones' => array( 'totalsType' => '' ),
'Valor Neto' => array( 'totalsType' => '' ),
'Tipo Beneficiario' => array( 'totalsType' => '' ),
'Vigencia Presupuestal' => array( 'totalsType' => '' ),
'Tipo Identificacion' => array( 'totalsType' => '' ),
'Identificacion' => array( 'totalsType' => '' ),
'Nombre Razon Social' => array( 'totalsType' => '' ),
'Medio de Pago' => array( 'totalsType' => '' ),
'Tipo Cuenta' => array( 'totalsType' => '' ),
'Numero Cuenta' => array( 'totalsType' => '' ),
'Estado Cuenta' => array( 'totalsType' => '' ),
'Entidad Nit' => array( 'totalsType' => '' ),
'Entidad Descripcion' => array( 'totalsType' => '' ),
'Dependencia' => array( 'totalsType' => '' ),
'Dependencia Descripcion' => array( 'totalsType' => '' ),
'Rubro' => array( 'totalsType' => '' ),
'Descripcion' => array( 'totalsType' => '' ),
'Fuente' => array( 'totalsType' => '' ),
'Recurso' => array( 'totalsType' => '' ),
'Sit' => array( 'totalsType' => '' ),
'Valor Pesos' => array( 'totalsType' => '' ),
'Valor Moneda' => array( 'totalsType' => '' ),
'Valor Reintegrado Pesos' => array( 'totalsType' => '' ),
'Valor Reintegrado Moneda' => array( 'totalsType' => '' ),
'Tesoreria Pagadora' => array( 'totalsType' => '' ),
'Identificacion Pagaduria' => array( 'totalsType' => '' ),
'Cuenta Pagaduria' => array( 'totalsType' => '' ),
'Endosada' => array( 'totalsType' => '' ),
'Tipo Identificacion1' => array( 'totalsType' => '' ),
'Identificacion1' => array( 'totalsType' => '' ),
'Razon social' => array( 'totalsType' => '' ),
'Numero Cuenta1' => array( 'totalsType' => '' ),
'Concepto Pago' => array( 'totalsType' => '' ),
'Solicitud CDP' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'Compromisos' => array( 'totalsType' => '' ),
'Cuentas por Pagar' => array( 'totalsType' => '' ),
'Fecha Cuentas por Pagar' => array( 'totalsType' => '' ),
'Obligaciones' => array( 'totalsType' => '' ),
'Ordenes de Pago' => array( 'totalsType' => '' ),
'Reintegros' => array( 'totalsType' => '' ),
'Fecha Doc Soporte Compromiso' => array( 'totalsType' => '' ),
'Tipo Doc Soporte Compromiso' => array( 'totalsType' => '' ),
'Num Doc Soporte Compromiso' => array( 'totalsType' => '' ),
'Objeto del Compromiso' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'OP_ID',
'Numero Documento',
'Fecha de pago',
'Estado',
'Valor Bruto',
'Valor Deducciones',
'Valor Neto',
'Tipo Beneficiario',
'Vigencia Presupuestal',
'Tipo Identificacion',
'Identificacion',
'Nombre Razon Social',
'Medio de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Fuente',
'Recurso',
'Sit',
'Valor Pesos',
'Valor Moneda',
'Valor Reintegrado Pesos',
'Valor Reintegrado Moneda',
'Tesoreria Pagadora',
'Identificacion Pagaduria',
'Cuenta Pagaduria',
'Endosada',
'Tipo Identificacion1',
'Identificacion1',
'Razon social',
'Numero Cuenta1',
'Concepto Pago',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Fecha Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros',
'Fecha Doc Soporte Compromiso',
'Tipo Doc Soporte Compromiso',
'Num Doc Soporte Compromiso',
'Objeto del Compromiso',
'Fecha de Registro' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'OP_ID' => array( 'simple_grid_field',
'simple_grid_field51' ),
'Numero Documento' => array( 'simple_grid_field1',
'simple_grid_field52' ),
'Fecha de pago' => array( 'simple_grid_field2',
'simple_grid_field53' ),
'Estado' => array( 'simple_grid_field3',
'simple_grid_field54' ),
'Valor Bruto' => array( 'simple_grid_field4',
'simple_grid_field55' ),
'Valor Deducciones' => array( 'simple_grid_field5',
'simple_grid_field56' ),
'Valor Neto' => array( 'simple_grid_field6',
'simple_grid_field57' ),
'Tipo Beneficiario' => array( 'simple_grid_field7',
'simple_grid_field58' ),
'Vigencia Presupuestal' => array( 'simple_grid_field8',
'simple_grid_field59' ),
'Tipo Identificacion' => array( 'simple_grid_field9',
'simple_grid_field60' ),
'Identificacion' => array( 'simple_grid_field10',
'simple_grid_field61' ),
'Nombre Razon Social' => array( 'simple_grid_field11',
'simple_grid_field62' ),
'Medio de Pago' => array( 'simple_grid_field12',
'simple_grid_field63' ),
'Tipo Cuenta' => array( 'simple_grid_field13',
'simple_grid_field64' ),
'Numero Cuenta' => array( 'simple_grid_field14',
'simple_grid_field65' ),
'Estado Cuenta' => array( 'simple_grid_field15',
'simple_grid_field66' ),
'Entidad Nit' => array( 'simple_grid_field16',
'simple_grid_field67' ),
'Entidad Descripcion' => array( 'simple_grid_field17',
'simple_grid_field68' ),
'Dependencia' => array( 'simple_grid_field18',
'simple_grid_field69' ),
'Dependencia Descripcion' => array( 'simple_grid_field19',
'simple_grid_field70' ),
'Rubro' => array( 'simple_grid_field20',
'simple_grid_field71' ),
'Descripcion' => array( 'simple_grid_field21',
'simple_grid_field72' ),
'Fuente' => array( 'simple_grid_field22',
'simple_grid_field73' ),
'Recurso' => array( 'simple_grid_field23',
'simple_grid_field74' ),
'Sit' => array( 'simple_grid_field24',
'simple_grid_field75' ),
'Valor Pesos' => array( 'simple_grid_field25',
'simple_grid_field76' ),
'Valor Moneda' => array( 'simple_grid_field26',
'simple_grid_field77' ),
'Valor Reintegrado Pesos' => array( 'simple_grid_field27',
'simple_grid_field78' ),
'Valor Reintegrado Moneda' => array( 'simple_grid_field28',
'simple_grid_field79' ),
'Tesoreria Pagadora' => array( 'simple_grid_field29',
'simple_grid_field80' ),
'Identificacion Pagaduria' => array( 'simple_grid_field30',
'simple_grid_field81' ),
'Cuenta Pagaduria' => array( 'simple_grid_field31',
'simple_grid_field82' ),
'Endosada' => array( 'simple_grid_field32',
'simple_grid_field83' ),
'Tipo Identificacion1' => array( 'simple_grid_field33',
'simple_grid_field84' ),
'Identificacion1' => array( 'simple_grid_field34',
'simple_grid_field85' ),
'Razon social' => array( 'simple_grid_field35',
'simple_grid_field86' ),
'Numero Cuenta1' => array( 'simple_grid_field36',
'simple_grid_field87' ),
'Concepto Pago' => array( 'simple_grid_field37',
'simple_grid_field88' ),
'Solicitud CDP' => array( 'simple_grid_field38',
'simple_grid_field89' ),
'CDP' => array( 'simple_grid_field39',
'simple_grid_field90' ),
'Compromisos' => array( 'simple_grid_field40',
'simple_grid_field91' ),
'Cuentas por Pagar' => array( 'simple_grid_field41',
'simple_grid_field92' ),
'Fecha Cuentas por Pagar' => array( 'simple_grid_field42',
'simple_grid_field93' ),
'Obligaciones' => array( 'simple_grid_field43',
'simple_grid_field94' ),
'Ordenes de Pago' => array( 'simple_grid_field44',
'simple_grid_field95' ),
'Reintegros' => array( 'simple_grid_field45',
'simple_grid_field96' ),
'Fecha Doc Soporte Compromiso' => array( 'simple_grid_field46',
'simple_grid_field97' ),
'Tipo Doc Soporte Compromiso' => array( 'simple_grid_field47',
'simple_grid_field98' ),
'Num Doc Soporte Compromiso' => array( 'simple_grid_field48',
'simple_grid_field99' ),
'Objeto del Compromiso' => array( 'simple_grid_field49',
'simple_grid_field100' ),
'Fecha de Registro' => array( 'simple_grid_field50',
'simple_grid_field101' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field51',
'simple_grid_field',
'simple_grid_field52',
'simple_grid_field1',
'simple_grid_field53',
'simple_grid_field2',
'simple_grid_field54',
'simple_grid_field3',
'simple_grid_field55',
'simple_grid_field4',
'simple_grid_field56',
'simple_grid_field5',
'simple_grid_field57',
'simple_grid_field6',
'simple_grid_field58',
'simple_grid_field7',
'simple_grid_field59',
'simple_grid_field8',
'simple_grid_field60',
'simple_grid_field9',
'simple_grid_field61',
'simple_grid_field10',
'simple_grid_field62',
'simple_grid_field11',
'simple_grid_field63',
'simple_grid_field12',
'simple_grid_field64',
'simple_grid_field13',
'simple_grid_field65',
'simple_grid_field14',
'simple_grid_field66',
'simple_grid_field15',
'simple_grid_field67',
'simple_grid_field16',
'simple_grid_field68',
'simple_grid_field17',
'simple_grid_field69',
'simple_grid_field18',
'simple_grid_field70',
'simple_grid_field19',
'simple_grid_field71',
'simple_grid_field20',
'simple_grid_field72',
'simple_grid_field21',
'simple_grid_field73',
'simple_grid_field22',
'simple_grid_field74',
'simple_grid_field23',
'simple_grid_field75',
'simple_grid_field24',
'simple_grid_field76',
'simple_grid_field25',
'simple_grid_field77',
'simple_grid_field26',
'simple_grid_field78',
'simple_grid_field27',
'simple_grid_field79',
'simple_grid_field28',
'simple_grid_field80',
'simple_grid_field29',
'simple_grid_field81',
'simple_grid_field30',
'simple_grid_field82',
'simple_grid_field31',
'simple_grid_field83',
'simple_grid_field32',
'simple_grid_field84',
'simple_grid_field33',
'simple_grid_field85',
'simple_grid_field34',
'simple_grid_field86',
'simple_grid_field35',
'simple_grid_field87',
'simple_grid_field36',
'simple_grid_field88',
'simple_grid_field37',
'simple_grid_field89',
'simple_grid_field38',
'simple_grid_field90',
'simple_grid_field39',
'simple_grid_field91',
'simple_grid_field40',
'simple_grid_field92',
'simple_grid_field41',
'simple_grid_field93',
'simple_grid_field42',
'simple_grid_field94',
'simple_grid_field43',
'simple_grid_field95',
'simple_grid_field44',
'simple_grid_field96',
'simple_grid_field45',
'simple_grid_field97',
'simple_grid_field46',
'simple_grid_field98',
'simple_grid_field47',
'simple_grid_field99',
'simple_grid_field48',
'simple_grid_field100',
'simple_grid_field49',
'simple_grid_field101',
'simple_grid_field50' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field51' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field90' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field91' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field92' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field93' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field94' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field95' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field96' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field97' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field98' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field99' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field100' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field101' => 'grid',
'simple_grid_field50' => 'grid' ),
'itemLocations' => array( 'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field90' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field91' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field92' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field93' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field94' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field95' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ),
'simple_grid_field96' => array( 'location' => 'grid',
'cellId' => 'headcell_field45' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field45' ),
'simple_grid_field97' => array( 'location' => 'grid',
'cellId' => 'headcell_field46' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ),
'simple_grid_field98' => array( 'location' => 'grid',
'cellId' => 'headcell_field47' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field47' ),
'simple_grid_field99' => array( 'location' => 'grid',
'cellId' => 'headcell_field48' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field48' ),
'simple_grid_field100' => array( 'location' => 'grid',
'cellId' => 'headcell_field49' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field49' ),
'simple_grid_field101' => array( 'location' => 'grid',
'cellId' => 'headcell_field50' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_field50' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50' ),
'grid_field_label' => array( 'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89',
'simple_grid_field90',
'simple_grid_field91',
'simple_grid_field92',
'simple_grid_field93',
'simple_grid_field94',
'simple_grid_field95',
'simple_grid_field96',
'simple_grid_field97',
'simple_grid_field98',
'simple_grid_field99',
'simple_grid_field100',
'simple_grid_field101' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'OP_ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Numero_Documento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_de_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Bruto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Deducciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Neto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Beneficiario_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Vigencia_Presupuestal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Identificacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Identificacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Nombre_Razon_Social_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Medio_de_Pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Numero_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'Estado_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'Entidad_Nit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'Entidad_Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'Dependencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'Dependencia_Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'Rubro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'Fuente_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'Recurso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'Sit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Pesos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Moneda_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Reintegrado_Pesos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Reintegrado_Moneda_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'Tesoreria_Pagadora_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'Identificacion_Pagaduria_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'Cuenta_Pagaduria_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'Endosada_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Identificacion1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'Identificacion1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'Razon_social_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'Numero_Cuenta1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'Concepto_Pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'Solicitud_CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field90' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'Compromisos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field91' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'Cuentas_por_Pagar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field92' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_Cuentas_por_Pagar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field93' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'Obligaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field94' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'Ordenes_de_Pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field95' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 0 ),
'tags' => array( 'Reintegros_fieldheadercolumn' ),
'items' => array( 'simple_grid_field96' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_Doc_Soporte_Compromiso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field97' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Doc_Soporte_Compromiso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field98' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 0 ),
'tags' => array( 'Num_Doc_Soporte_Compromiso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field99' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 0 ),
'tags' => array( 'Objeto_del_Compromiso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field100' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_de_Registro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field101' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'OP_ID_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Numero_Documento_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_de_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Estado_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Bruto_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Deducciones_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Neto_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Beneficiario_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Vigencia_Presupuestal_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Identificacion_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Identificacion_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Nombre_Razon_Social_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Medio_de_Pago_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Numero_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'Estado_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'Entidad_Nit_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'Entidad_Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'Dependencia_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'Dependencia_Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'Rubro_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'Fuente_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'Recurso_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'Sit_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Pesos_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Moneda_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Reintegrado_Pesos_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Reintegrado_Moneda_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'Tesoreria_Pagadora_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'Identificacion_Pagaduria_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'Cuenta_Pagaduria_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'Endosada_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Identificacion1_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'Identificacion1_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'Razon_social_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'Numero_Cuenta1_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'Concepto_Pago_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'Solicitud_CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'Compromisos_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'Cuentas_por_Pagar_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_Cuentas_por_Pagar_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'Obligaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'Ordenes_de_Pago_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 1 ),
'tags' => array( 'Reintegros_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_Doc_Soporte_Compromiso_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Doc_Soporte_Compromiso_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 1 ),
'tags' => array( 'Num_Doc_Soporte_Compromiso_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 1 ),
'tags' => array( 'Objeto_del_Compromiso_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_de_Registro_fieldcolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 51,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field46' ),
array( 'cell' => 'headcell_field47' ),
array( 'cell' => 'headcell_field48' ),
array( 'cell' => 'headcell_field49' ),
array( 'cell' => 'headcell_field50' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'cell_field50' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ),
array( 'cell' => 'footcell_field45' ),
array( 'cell' => 'footcell_field46' ),
array( 'cell' => 'footcell_field47' ),
array( 'cell' => 'footcell_field48' ),
array( 'cell' => 'footcell_field49' ),
array( 'cell' => 'footcell_field50' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'OP_ID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'OP_ID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'Numero Documento',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Numero Documento',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'Fecha de pago',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Fecha de pago',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'Estado',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Estado',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'Valor Bruto',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'Valor Bruto',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'Valor Deducciones',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'Valor Deducciones',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'Valor Neto',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'Valor Neto',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'Tipo Beneficiario',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'Tipo Beneficiario',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'Vigencia Presupuestal',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'Vigencia Presupuestal',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'Tipo Identificacion',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'Tipo Identificacion',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'Identificacion',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'Identificacion',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'Nombre Razon Social',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'Nombre Razon Social',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'Medio de Pago',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'Medio de Pago',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'Tipo Cuenta',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'Tipo Cuenta',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'Numero Cuenta',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'Numero Cuenta',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'Estado Cuenta',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'Estado Cuenta',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'Entidad Nit',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'Entidad Nit',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'Entidad Descripcion',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'Entidad Descripcion',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'Dependencia',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'Dependencia',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'Dependencia Descripcion',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'Dependencia Descripcion',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'Rubro',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'Rubro',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'Descripcion',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'Descripcion',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'Fuente',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'Fuente',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'Recurso',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'Recurso',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'Sit',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'Sit',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'Valor Pesos',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'Valor Pesos',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'Valor Moneda',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'Valor Moneda',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'Valor Reintegrado Pesos',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'Valor Reintegrado Pesos',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'Valor Reintegrado Moneda',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'Valor Reintegrado Moneda',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'Tesoreria Pagadora',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'Tesoreria Pagadora',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'Identificacion Pagaduria',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'Identificacion Pagaduria',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'Cuenta Pagaduria',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'Cuenta Pagaduria',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'Endosada',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'Endosada',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'Tipo Identificacion1',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'Tipo Identificacion1',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'Identificacion1',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'Identificacion1',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'Razon social',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'Razon social',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'Numero Cuenta1',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'Numero Cuenta1',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'Concepto Pago',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'Concepto Pago',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'Solicitud CDP',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'Solicitud CDP',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field90' ),
'field' => 'CDP',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'CDP',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field91' ),
'field' => 'Compromisos',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'Compromisos',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field92' ),
'field' => 'Cuentas por Pagar',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'Cuentas por Pagar',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field93' ),
'field' => 'Fecha Cuentas por Pagar',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'Fecha Cuentas por Pagar',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field94' ),
'field' => 'Obligaciones',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'Obligaciones',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field95' ),
'field' => 'Ordenes de Pago',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'Ordenes de Pago',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field45' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field96' ),
'field' => 'Reintegros',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'Reintegros',
'columnName' => 'field' ),
'footcell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field97' ),
'field' => 'Fecha Doc Soporte Compromiso',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'Fecha Doc Soporte Compromiso',
'columnName' => 'field' ),
'footcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field47' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field98' ),
'field' => 'Tipo Doc Soporte Compromiso',
'columnName' => 'field' ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'Tipo Doc Soporte Compromiso',
'columnName' => 'field' ),
'footcell_field47' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field48' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field99' ),
'field' => 'Num Doc Soporte Compromiso',
'columnName' => 'field' ),
'cell_field48' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'Num Doc Soporte Compromiso',
'columnName' => 'field' ),
'footcell_field48' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field49' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field100' ),
'field' => 'Objeto del Compromiso',
'columnName' => 'field' ),
'cell_field49' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'Objeto del Compromiso',
'columnName' => 'field' ),
'footcell_field49' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field50' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field101' ),
'field' => 'Fecha de Registro',
'columnName' => 'field' ),
'cell_field50' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'Fecha de Registro',
'columnName' => 'field' ),
'footcell_field50' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'OP_ID',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'OP_ID' ),
'simple_grid_field1' => array( 'field' => 'Numero Documento',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'Numero Documento' ),
'simple_grid_field2' => array( 'field' => 'Fecha de pago',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'Fecha de pago' ),
'simple_grid_field3' => array( 'field' => 'Estado',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'Estado' ),
'simple_grid_field4' => array( 'field' => 'Valor Bruto',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'Valor Bruto' ),
'simple_grid_field5' => array( 'field' => 'Valor Deducciones',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'Valor Deducciones' ),
'simple_grid_field6' => array( 'field' => 'Valor Neto',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'Valor Neto' ),
'simple_grid_field7' => array( 'field' => 'Tipo Beneficiario',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Beneficiario' ),
'simple_grid_field8' => array( 'field' => 'Vigencia Presupuestal',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'Vigencia Presupuestal' ),
'simple_grid_field9' => array( 'field' => 'Tipo Identificacion',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Identificacion' ),
'simple_grid_field10' => array( 'field' => 'Identificacion',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'Identificacion' ),
'simple_grid_field11' => array( 'field' => 'Nombre Razon Social',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'Nombre Razon Social' ),
'simple_grid_field12' => array( 'field' => 'Medio de Pago',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'Medio de Pago' ),
'simple_grid_field13' => array( 'field' => 'Tipo Cuenta',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Cuenta' ),
'simple_grid_field14' => array( 'field' => 'Numero Cuenta',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'Numero Cuenta' ),
'simple_grid_field15' => array( 'field' => 'Estado Cuenta',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'Estado Cuenta' ),
'simple_grid_field16' => array( 'field' => 'Entidad Nit',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'Entidad Nit' ),
'simple_grid_field17' => array( 'field' => 'Entidad Descripcion',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'Entidad Descripcion' ),
'simple_grid_field18' => array( 'field' => 'Dependencia',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'Dependencia' ),
'simple_grid_field19' => array( 'field' => 'Dependencia Descripcion',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'Dependencia Descripcion' ),
'simple_grid_field20' => array( 'field' => 'Rubro',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'Rubro' ),
'simple_grid_field21' => array( 'field' => 'Descripcion',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'Descripcion' ),
'simple_grid_field22' => array( 'field' => 'Fuente',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'Fuente' ),
'simple_grid_field23' => array( 'field' => 'Recurso',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'Recurso' ),
'simple_grid_field24' => array( 'field' => 'Sit',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'Sit' ),
'simple_grid_field25' => array( 'field' => 'Valor Pesos',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'Valor Pesos' ),
'simple_grid_field26' => array( 'field' => 'Valor Moneda',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'Valor Moneda' ),
'simple_grid_field27' => array( 'field' => 'Valor Reintegrado Pesos',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'Valor Reintegrado Pesos' ),
'simple_grid_field28' => array( 'field' => 'Valor Reintegrado Moneda',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'Valor Reintegrado Moneda' ),
'simple_grid_field29' => array( 'field' => 'Tesoreria Pagadora',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'Tesoreria Pagadora' ),
'simple_grid_field30' => array( 'field' => 'Identificacion Pagaduria',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'Identificacion Pagaduria' ),
'simple_grid_field31' => array( 'field' => 'Cuenta Pagaduria',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'Cuenta Pagaduria' ),
'simple_grid_field32' => array( 'field' => 'Endosada',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'Endosada' ),
'simple_grid_field33' => array( 'field' => 'Tipo Identificacion1',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Identificacion1' ),
'simple_grid_field34' => array( 'field' => 'Identificacion1',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'Identificacion1' ),
'simple_grid_field35' => array( 'field' => 'Razon social',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'Razon social' ),
'simple_grid_field36' => array( 'field' => 'Numero Cuenta1',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'Numero Cuenta1' ),
'simple_grid_field37' => array( 'field' => 'Concepto Pago',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'Concepto Pago' ),
'simple_grid_field38' => array( 'field' => 'Solicitud CDP',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'Solicitud CDP' ),
'simple_grid_field39' => array( 'field' => 'CDP',
'type' => 'grid_field' ),
'simple_grid_field90' => array( 'type' => 'grid_field_label',
'field' => 'CDP' ),
'simple_grid_field40' => array( 'field' => 'Compromisos',
'type' => 'grid_field' ),
'simple_grid_field91' => array( 'type' => 'grid_field_label',
'field' => 'Compromisos' ),
'simple_grid_field41' => array( 'field' => 'Cuentas por Pagar',
'type' => 'grid_field' ),
'simple_grid_field92' => array( 'type' => 'grid_field_label',
'field' => 'Cuentas por Pagar' ),
'simple_grid_field42' => array( 'field' => 'Fecha Cuentas por Pagar',
'type' => 'grid_field' ),
'simple_grid_field93' => array( 'type' => 'grid_field_label',
'field' => 'Fecha Cuentas por Pagar' ),
'simple_grid_field43' => array( 'field' => 'Obligaciones',
'type' => 'grid_field' ),
'simple_grid_field94' => array( 'type' => 'grid_field_label',
'field' => 'Obligaciones' ),
'simple_grid_field44' => array( 'field' => 'Ordenes de Pago',
'type' => 'grid_field' ),
'simple_grid_field95' => array( 'type' => 'grid_field_label',
'field' => 'Ordenes de Pago' ),
'simple_grid_field45' => array( 'field' => 'Reintegros',
'type' => 'grid_field' ),
'simple_grid_field96' => array( 'type' => 'grid_field_label',
'field' => 'Reintegros' ),
'simple_grid_field46' => array( 'field' => 'Fecha Doc Soporte Compromiso',
'type' => 'grid_field' ),
'simple_grid_field97' => array( 'type' => 'grid_field_label',
'field' => 'Fecha Doc Soporte Compromiso' ),
'simple_grid_field47' => array( 'field' => 'Tipo Doc Soporte Compromiso',
'type' => 'grid_field' ),
'simple_grid_field98' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Doc Soporte Compromiso' ),
'simple_grid_field48' => array( 'field' => 'Num Doc Soporte Compromiso',
'type' => 'grid_field' ),
'simple_grid_field99' => array( 'type' => 'grid_field_label',
'field' => 'Num Doc Soporte Compromiso' ),
'simple_grid_field49' => array( 'field' => 'Objeto del Compromiso',
'type' => 'grid_field' ),
'simple_grid_field100' => array( 'type' => 'grid_field_label',
'field' => 'Objeto del Compromiso' ),
'simple_grid_field50' => array( 'field' => 'Fecha de Registro',
'type' => 'grid_field' ),
'simple_grid_field101' => array( 'type' => 'grid_field_label',
'field' => 'Fecha de Registro' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>