<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'OP_ID',
'Numero Documento',
'Fecha de Registro',
'Fecha de pago',
'Estado',
'Valor Bruto',
'Valor Deducciones',
'Valor Neto',
'Tipo Beneficiario',
'Vigencia Presupuestal',
'Tipo Identificacion',
'Identificacion',
'Nombre Razon Social',
'Medio de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Fuente',
'Recurso',
'Sit',
'Valor Pesos',
'Valor Moneda',
'Valor Reintegrado Pesos',
'Valor Reintegrado Moneda',
'Tesoreria Pagadora',
'Identificacion Pagaduria',
'Cuenta Pagaduria',
'Endosada',
'Tipo Identificacion1',
'Identificacion1',
'Razon social',
'Numero Cuenta1',
'Concepto Pago',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Fecha Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros',
'Fecha Doc Soporte Compromiso',
'Tipo Doc Soporte Compromiso',
'Num Doc Soporte Compromiso',
'Objeto del Compromiso' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'OP_ID' => array( 'import_field' ),
'Numero Documento' => array( 'import_field1' ),
'Fecha de Registro' => array( 'import_field2' ),
'Fecha de pago' => array( 'import_field3' ),
'Estado' => array( 'import_field4' ),
'Valor Bruto' => array( 'import_field5' ),
'Valor Deducciones' => array( 'import_field6' ),
'Valor Neto' => array( 'import_field7' ),
'Tipo Beneficiario' => array( 'import_field8' ),
'Vigencia Presupuestal' => array( 'import_field9' ),
'Tipo Identificacion' => array( 'import_field10' ),
'Identificacion' => array( 'import_field11' ),
'Nombre Razon Social' => array( 'import_field12' ),
'Medio de Pago' => array( 'import_field13' ),
'Tipo Cuenta' => array( 'import_field14' ),
'Numero Cuenta' => array( 'import_field15' ),
'Estado Cuenta' => array( 'import_field16' ),
'Entidad Nit' => array( 'import_field17' ),
'Entidad Descripcion' => array( 'import_field18' ),
'Dependencia' => array( 'import_field19' ),
'Dependencia Descripcion' => array( 'import_field20' ),
'Rubro' => array( 'import_field21' ),
'Descripcion' => array( 'import_field22' ),
'Fuente' => array( 'import_field23' ),
'Recurso' => array( 'import_field24' ),
'Sit' => array( 'import_field25' ),
'Valor Pesos' => array( 'import_field26' ),
'Valor Moneda' => array( 'import_field27' ),
'Valor Reintegrado Pesos' => array( 'import_field28' ),
'Valor Reintegrado Moneda' => array( 'import_field29' ),
'Tesoreria Pagadora' => array( 'import_field30' ),
'Identificacion Pagaduria' => array( 'import_field31' ),
'Cuenta Pagaduria' => array( 'import_field32' ),
'Endosada' => array( 'import_field33' ),
'Tipo Identificacion1' => array( 'import_field34' ),
'Identificacion1' => array( 'import_field35' ),
'Razon social' => array( 'import_field36' ),
'Numero Cuenta1' => array( 'import_field37' ),
'Concepto Pago' => array( 'import_field38' ),
'Solicitud CDP' => array( 'import_field39' ),
'CDP' => array( 'import_field40' ),
'Compromisos' => array( 'import_field41' ),
'Cuentas por Pagar' => array( 'import_field42' ),
'Fecha Cuentas por Pagar' => array( 'import_field43' ),
'Obligaciones' => array( 'import_field44' ),
'Ordenes de Pago' => array( 'import_field45' ),
'Reintegros' => array( 'import_field46' ),
'Fecha Doc Soporte Compromiso' => array( 'import_field47' ),
'Tipo Doc Soporte Compromiso' => array( 'import_field48' ),
'Num Doc Soporte Compromiso' => array( 'import_field49' ),
'Objeto del Compromiso' => array( 'import_field50' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'OP_ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Numero Documento',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Fecha de Registro',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Fecha de pago',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Valor Bruto',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Valor Deducciones',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Valor Neto',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Tipo Beneficiario',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Vigencia Presupuestal',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Tipo Identificacion',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Identificacion',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Nombre Razon Social',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Medio de Pago',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Tipo Cuenta',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Numero Cuenta',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Estado Cuenta',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Entidad Nit',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Entidad Descripcion',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Dependencia',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Dependencia Descripcion',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Rubro',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'Descripcion',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'Fuente',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'Recurso',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'Sit',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'Valor Pesos',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Valor Moneda',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Valor Reintegrado Pesos',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'Valor Reintegrado Moneda',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'Tesoreria Pagadora',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'Identificacion Pagaduria',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'Cuenta Pagaduria',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'Endosada',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'Tipo Identificacion1',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'Identificacion1',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'Razon social',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'Numero Cuenta1',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'Concepto Pago',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'Solicitud CDP',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'CDP',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'Compromisos',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'Cuentas por Pagar',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'Fecha Cuentas por Pagar',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'Obligaciones',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'Ordenes de Pago',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'Reintegros',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'Fecha Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'Tipo Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'Num Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'Objeto del Compromiso',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>