<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'idusrglobal' => array( 'totalsType' => '' ),
'id_fk' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'usr_nombresfull' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_inicial' => array( 'totalsType' => '' ),
'usr_sessini' => array( 'totalsType' => '' ),
'usr_image' => array( 'totalsType' => '' ),
'usr_status_nomina' => array( 'totalsType' => '' ),
'usr_status' => array( 'totalsType' => '' ),
'usr_rdnkey' => array( 'totalsType' => '' ),
'usr_type_vinc' => array( 'totalsType' => '' ),
'usr_type_vinculacion' => array( 'totalsType' => '' ),
'usr_status_sol' => array( 'totalsType' => '' ),
'usr_dependencia' => array( 'totalsType' => '' ),
'user_dep' => array( 'totalsType' => '' ),
'usr_entidad' => array( 'totalsType' => '' ),
'usr_not' => array( 'totalsType' => '' ),
'usr_not_msj' => array( 'totalsType' => '' ),
'usr_jefe' => array( 'totalsType' => '' ),
'usr_minequipo_lider' => array( 'totalsType' => '' ),
'usr_minequipo_grupo' => array( 'totalsType' => '' ),
'global_rol_me' => array( 'totalsType' => '' ),
'global_rol_gh' => array( 'totalsType' => '' ),
'global_rol_almacen' => array( 'totalsType' => '' ),
'global_rol_ci' => array( 'totalsType' => '' ),
'global_rol_contratos' => array( 'totalsType' => '' ),
'global_rol_hojar' => array( 'totalsType' => '' ),
'global_rol_inmuebles' => array( 'totalsType' => '' ),
'global_rol_siis' => array( 'totalsType' => '' ),
'global_rol_cpanel' => array( 'totalsType' => '' ),
'global_rol_dashboard' => array( 'totalsType' => '' ),
'global_rol_zf' => array( 'totalsType' => '' ),
'global_rol_sipi' => array( 'totalsType' => '' ),
'global_rol_cej' => array( 'totalsType' => '' ),
'global_rol_jc3' => array( 'totalsType' => '' ),
'global_rol_th' => array( 'totalsType' => '' ),
'global_rol_sid' => array( 'totalsType' => '' ),
'global_rol' => array( 'totalsType' => '' ),
'global_rol_cont' => array( 'totalsType' => '' ),
'globla_rol_ct' => array( 'totalsType' => '' ),
'global_rol_procjur' => array( 'totalsType' => '' ),
'global_rol_comacc' => array( 'totalsType' => '' ),
'global_rol_gestion' => array( 'totalsType' => '' ),
'global_rol_ciudadano' => array( 'totalsType' => '' ),
'global_rol_ciudadano_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_time' => array( 'totalsType' => '' ),
'sys_ntries_usr' => array( 'totalsType' => '' ),
'sys_registrationdate_usr' => array( 'totalsType' => '' ),
'sys_expiration_usr' => array( 'totalsType' => '' ),
'sys_disabledate_usr' => array( 'totalsType' => '' ),
'sys_upd_fecha' => array( 'totalsType' => '' ),
'sys_upd_user' => array( 'totalsType' => '' ),
'sys_upd_time' => array( 'totalsType' => '' ),
'sys_update_info' => array( 'totalsType' => '' ),
'sys_update_family_info' => array( 'totalsType' => '' ),
'usr_update_almacen' => array( 'totalsType' => '' ),
'sys_anio' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'usr_regpago' => array( 'totalsType' => '' ),
'usr_extension' => array( 'totalsType' => '' ),
'usr_piso' => array( 'totalsType' => '' ),
'usr_datebirth' => array( 'totalsType' => '' ),
'ctrl_pedidoalmacen' => array( 'totalsType' => '' ),
'ctrl_contacto' => array( 'totalsType' => '' ),
'usr_emergencia' => array( 'totalsType' => '' ),
'upd_date' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'habilita_almacen' => array( 'totalsType' => '' ),
'estado_vinculacion_mincit' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'phone1' => array( 'totalsType' => '' ),
'usr_directivo' => array( 'totalsType' => '' ),
'usr_dep_sup' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Username',
'usr_email',
'usr_nombresfull',
'usr_status_nomina' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Username' => array( 'simple_grid_field2',
'simple_grid_field3' ),
'usr_email' => array( 'simple_grid_field4',
'simple_grid_field5' ),
'usr_nombresfull' => array( 'simple_grid_field',
'simple_grid_field6' ),
'usr_status_nomina' => array( 'simple_grid_field1',
'simple_grid_field7' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'master_info' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field3',
'simple_grid_field2',
'simple_grid_field5',
'simple_grid_field4',
'simple_grid_field6',
'simple_grid_field',
'simple_grid_field7',
'simple_grid_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field3' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field1' => 'grid' ),
'itemLocations' => array( 'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'master_info' => array( 'master_info' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field',
'simple_grid_field1' ),
'grid_field_label' => array( 'simple_grid_field3',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'usr_email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'usr_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'usr_status_nomina_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'Username_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'usr_email_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'usr_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'usr_status_nomina_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Username',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Username',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'usr_email',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'usr_email',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'usr_nombresfull',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'usr_nombresfull',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'usr_status_nomina',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'usr_status_nomina',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'funcionario' => 'true' ) ),
'simple_grid_field2' => array( 'field' => 'Username',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'Username' ),
'simple_grid_field4' => array( 'field' => 'usr_email',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'usr_email' ),
'simple_grid_field' => array( 'field' => 'usr_nombresfull',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'usr_nombresfull' ),
'simple_grid_field1' => array( 'field' => 'usr_status_nomina',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'usr_status_nomina' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>