<?php
			$optionsArray = array( 'totals' => array( 'idusrglobal' => array( 'totalsType' => '' ),
'id_fk' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'usr_nombresfull' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_inicial' => array( 'totalsType' => '' ),
'usr_sessini' => array( 'totalsType' => '' ),
'usr_image' => array( 'totalsType' => '' ),
'usr_status_nomina' => array( 'totalsType' => '' ),
'usr_status' => array( 'totalsType' => '' ),
'usr_rdnkey' => array( 'totalsType' => '' ),
'usr_type_vinc' => array( 'totalsType' => '' ),
'usr_type_vinculacion' => array( 'totalsType' => '' ),
'usr_status_sol' => array( 'totalsType' => '' ),
'usr_dependencia' => array( 'totalsType' => '' ),
'user_dep' => array( 'totalsType' => '' ),
'usr_entidad' => array( 'totalsType' => '' ),
'usr_not' => array( 'totalsType' => '' ),
'usr_not_msj' => array( 'totalsType' => '' ),
'usr_jefe' => array( 'totalsType' => '' ),
'usr_minequipo_lider' => array( 'totalsType' => '' ),
'usr_minequipo_grupo' => array( 'totalsType' => '' ),
'global_rol_me' => array( 'totalsType' => '' ),
'global_rol_gh' => array( 'totalsType' => '' ),
'global_rol_almacen' => array( 'totalsType' => '' ),
'global_rol_ci' => array( 'totalsType' => '' ),
'global_rol_contratos' => array( 'totalsType' => '' ),
'global_rol_hojar' => array( 'totalsType' => '' ),
'global_rol_inmuebles' => array( 'totalsType' => '' ),
'global_rol_siis' => array( 'totalsType' => '' ),
'global_rol_cpanel' => array( 'totalsType' => '' ),
'global_rol_dashboard' => array( 'totalsType' => '' ),
'global_rol_zf' => array( 'totalsType' => '' ),
'global_rol_sipi' => array( 'totalsType' => '' ),
'global_rol_cej' => array( 'totalsType' => '' ),
'global_rol_jc3' => array( 'totalsType' => '' ),
'global_rol_th' => array( 'totalsType' => '' ),
'global_rol_sid' => array( 'totalsType' => '' ),
'global_rol' => array( 'totalsType' => '' ),
'global_rol_cont' => array( 'totalsType' => '' ),
'globla_rol_ct' => array( 'totalsType' => '' ),
'global_rol_procjur' => array( 'totalsType' => '' ),
'global_rol_comacc' => array( 'totalsType' => '' ),
'global_rol_gestion' => array( 'totalsType' => '' ),
'global_rol_ciudadano' => array( 'totalsType' => '' ),
'global_rol_ciudadano_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_time' => array( 'totalsType' => '' ),
'sys_ntries_usr' => array( 'totalsType' => '' ),
'sys_registrationdate_usr' => array( 'totalsType' => '' ),
'sys_expiration_usr' => array( 'totalsType' => '' ),
'sys_disabledate_usr' => array( 'totalsType' => '' ),
'sys_upd_fecha' => array( 'totalsType' => '' ),
'sys_upd_user' => array( 'totalsType' => '' ),
'sys_upd_time' => array( 'totalsType' => '' ),
'sys_update_info' => array( 'totalsType' => '' ),
'sys_update_family_info' => array( 'totalsType' => '' ),
'usr_update_almacen' => array( 'totalsType' => '' ),
'sys_anio' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'usr_regpago' => array( 'totalsType' => '' ),
'usr_extension' => array( 'totalsType' => '' ),
'usr_piso' => array( 'totalsType' => '' ),
'usr_datebirth' => array( 'totalsType' => '' ),
'ctrl_pedidoalmacen' => array( 'totalsType' => '' ),
'ctrl_contacto' => array( 'totalsType' => '' ),
'usr_emergencia' => array( 'totalsType' => '' ),
'upd_date' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'habilita_almacen' => array( 'totalsType' => '' ),
'estado_vinculacion_mincit' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'phone1' => array( 'totalsType' => '' ),
'usr_directivo' => array( 'totalsType' => '' ),
'usr_dep_sup' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Username',
'usr_email',
'usr_nombresfull',
'usr_status_nomina' ),
'exportFields' => array( 'Username',
'usr_email',
'usr_nombresfull',
'usr_status_nomina' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Username' => array( 'export_field2' ),
'usr_email' => array( 'export_field4' ),
'usr_nombresfull' => array( 'export_field' ),
'usr_status_nomina' => array( 'export_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field2',
'export_field4',
'export_field',
'export_field1' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field2',
'export_field4',
'export_field',
'export_field1' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field2',
'export_field4',
'export_field',
'export_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field2' => array( 'field' => 'Username',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'usr_email',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'usr_nombresfull',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'usr_status_nomina',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>