<?php
			$optionsArray = array( 'totals' => array( 'hr_id' => array( 'totalsType' => '' ),
'hr_concepto_id' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'hr_anio' => array( 'totalsType' => '' ),
'ctrlpagos_id_fk' => array( 'totalsType' => '' ),
'cxc_id_fk' => array( 'totalsType' => '' ),
'obligacion' => array( 'totalsType' => '' ),
'id_informe_fk' => array( 'totalsType' => '' ),
'hr_nit_contra_ta' => array( 'totalsType' => '' ),
'hr_asunto' => array( 'totalsType' => '' ),
'hr_valor' => array( 'totalsType' => '' ),
'hr_fechaingreso' => array( 'totalsType' => '' ),
'hr_fecha_salida' => array( 'totalsType' => '' ),
'hr_estado_firma' => array( 'totalsType' => '' ),
'hr_estado_numero' => array( 'totalsType' => '' ),
'hr_estado_fecha' => array( 'totalsType' => '' ),
'hr_estado_file' => array( 'totalsType' => '' ),
'hr_estado_user' => array( 'totalsType' => '' ),
'sys_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_user_actual' => array( 'totalsType' => '' ),
'sys_fecha_reg' => array( 'totalsType' => '' ),
'hr_file' => array( 'totalsType' => '' ),
'not_status' => array( 'totalsType' => '' ),
'not_time' => array( 'totalsType' => '' ),
'not_user' => array( 'totalsType' => '' ),
'not_date' => array( 'totalsType' => '' ),
'not_mail' => array( 'totalsType' => '' ),
'not_msg' => array( 'totalsType' => '' ),
'sysdate' => array( 'totalsType' => '' ),
'evento_type_id_fk' => array( 'totalsType' => '' ),
'user_from' => array( 'totalsType' => '' ),
'last_act_user' => array( 'totalsType' => '' ),
'hr_aprob_estado' => array( 'totalsType' => '' ),
'hr_aprob_fecha' => array( 'totalsType' => '' ),
'hr_aprob_user' => array( 'totalsType' => '' ),
'tercero_email_a' => array( 'totalsType' => '' ),
'tercero_email_b' => array( 'totalsType' => '' ),
'anio' => array( 'totalsType' => '' ),
'mes' => array( 'totalsType' => '' ),
'cont_num' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'hr_id',
'hr_concepto_id',
'id_cont_fk',
'hr_anio',
'hr_nit_contra_ta',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'not_user',
'not_date',
'not_mail',
'not_msg',
'sysdate',
'evento_type_id_fk',
'user_from',
'tercero_email_a',
'last_act_user',
'tercero_email_b',
'sys_dep',
'cont_num' ),
'exportFields' => array( 'hr_id',
'hr_concepto_id',
'id_cont_fk',
'hr_anio',
'hr_nit_contra_ta',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'not_user',
'not_date',
'not_mail',
'not_msg',
'sysdate',
'evento_type_id_fk',
'user_from',
'last_act_user',
'tercero_email_a',
'tercero_email_b',
'sys_dep',
'cont_num' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'hr_id' => array( 'export_field' ),
'hr_concepto_id' => array( 'export_field1' ),
'id_cont_fk' => array( 'export_field2' ),
'hr_anio' => array( 'export_field3' ),
'hr_nit_contra_ta' => array( 'export_field8' ),
'hr_asunto' => array( 'export_field9' ),
'hr_valor' => array( 'export_field10' ),
'hr_fechaingreso' => array( 'export_field11' ),
'sys_user' => array( 'export_field18' ),
'not_user' => array( 'export_field24' ),
'not_date' => array( 'export_field25' ),
'not_mail' => array( 'export_field26' ),
'not_msg' => array( 'export_field27' ),
'sysdate' => array( 'export_field28' ),
'evento_type_id_fk' => array( 'export_field29' ),
'user_from' => array( 'export_field30' ),
'tercero_email_a' => array( 'export_field31' ),
'last_act_user' => array( 'export_field32' ),
'tercero_email_b' => array( 'export_field36' ),
'sys_dep' => array( 'export_field4' ),
'cont_num' => array( 'export_field5' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field18',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field32',
'export_field31',
'export_field36',
'export_field4',
'export_field5' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field18' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field32' => 'grid',
'export_field31' => 'grid',
'export_field36' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field18',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field36',
'export_field4',
'export_field5' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field18',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field32',
'export_field31',
'export_field36',
'export_field4',
'export_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'hr_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'hr_concepto_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'id_cont_fk',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'hr_anio',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'hr_nit_contra_ta',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'hr_asunto',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'hr_valor',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'hr_fechaingreso',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'not_user',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'not_date',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'not_mail',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'not_msg',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'sysdate',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'evento_type_id_fk',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'user_from',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'tercero_email_a',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'last_act_user',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'tercero_email_b',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'sys_dep',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cont_num',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>