<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'hoja_ruta_2020_files' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ),
'hoja_ruta_2020_tracking' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ),
'q_info_cont' => array( 'displayPreview' => 1,
'previewPageId' => 'print1' ),
'hoja_ruta_ob' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ),
'hoja_ruta_op' => array( 'displayPreview' => 1,
'previewPageId' => 'print' ) ),
'totals' => array( 'hr_id' => array( 'totalsType' => '' ),
'hr_id_qr' => array( 'totalsType' => '' ),
'hr_concepto_id' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'hr_anio' => array( 'totalsType' => '' ),
'ctrlpagos_id_fk' => array( 'totalsType' => '' ),
'cxc_id_fk' => array( 'totalsType' => '' ),
'obligacion' => array( 'totalsType' => '' ),
'id_informe_fk' => array( 'totalsType' => '' ),
'hr_nit_contra_ta' => array( 'totalsType' => '' ),
'nombrecont' => array( 'totalsType' => '' ),
'hr_asunto' => array( 'totalsType' => '' ),
'hr_valor' => array( 'totalsType' => '' ),
'hr_fechaingreso' => array( 'totalsType' => '' ),
'hr_fecha_salida' => array( 'totalsType' => '' ),
'hr_estado_firma' => array( 'totalsType' => '' ),
'hr_estado_numero' => array( 'totalsType' => '' ),
'hr_estado_fecha' => array( 'totalsType' => '' ),
'hr_estado_file' => array( 'totalsType' => '' ),
'hr_estado_user' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_user_actual' => array( 'totalsType' => '' ),
'sys_fecha_reg' => array( 'totalsType' => '' ),
'hr_file' => array( 'totalsType' => '' ),
'not_status' => array( 'totalsType' => '' ),
'not_time' => array( 'totalsType' => '' ),
'not_user' => array( 'totalsType' => '' ),
'not_date' => array( 'totalsType' => '' ),
'not_mail' => array( 'totalsType' => '' ),
'not_msg' => array( 'totalsType' => '' ),
'sysdate' => array( 'totalsType' => '' ),
'evento_type_id_fk' => array( 'totalsType' => '' ),
'user_from' => array( 'totalsType' => '' ),
'last_act_user' => array( 'totalsType' => '' ),
'hr_aprob_estado' => array( 'totalsType' => '' ),
'hr_aprob_fecha' => array( 'totalsType' => '' ),
'hr_aprob_user' => array( 'totalsType' => '' ),
'tercero_email_a' => array( 'totalsType' => '' ),
'tercero_email_b' => array( 'totalsType' => '' ),
'anio' => array( 'totalsType' => '' ),
'mes' => array( 'totalsType' => '' ),
'sys_dep' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'hr_id',
'hr_id_qr',
'id_cont_fk',
'hr_anio',
'hr_nit_contra_ta',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'user_from',
'sys_dep',
'nombrecont' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'hr_id' => array( 'simple_grid_field',
'simple_grid_field5' ),
'hr_id_qr' => array( 'simple_grid_field1',
'simple_grid_field16' ),
'id_cont_fk' => array( 'simple_grid_field2',
'simple_grid_field6' ),
'hr_anio' => array( 'simple_grid_field3',
'simple_grid_field7' ),
'hr_nit_contra_ta' => array( 'simple_grid_field8',
'simple_grid_field12' ),
'hr_asunto' => array( 'simple_grid_field9',
'simple_grid_field13' ),
'hr_valor' => array( 'simple_grid_field10',
'simple_grid_field14' ),
'hr_fechaingreso' => array( 'simple_grid_field11',
'simple_grid_field15' ),
'sys_user' => array( 'simple_grid_field18',
'simple_grid_field19' ),
'user_from' => array( 'simple_grid_field30',
'simple_grid_field31' ),
'sys_dep' => array( 'simple_grid_field39',
'simple_grid_field40' ),
'nombrecont' => array( 'grid_field',
'grid_field_label' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'image' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'simple_grid_field5',
'simple_grid_field',
'simple_grid_field12',
'simple_grid_field8',
'simple_grid_field31',
'simple_grid_field30',
'simple_grid_field6',
'simple_grid_field2',
'grid_field_label',
'grid_field',
'simple_grid_field40',
'simple_grid_field39',
'simple_grid_field7',
'simple_grid_field3',
'simple_grid_field13',
'simple_grid_field9',
'simple_grid_field19',
'simple_grid_field18',
'simple_grid_field14',
'simple_grid_field10',
'simple_grid_field15',
'simple_grid_field11',
'simple_grid_field16',
'simple_grid_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'image' => 'top',
'print_pages' => 'above-grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'details_preview2' => 'grid',
'details_preview3' => 'grid',
'details_preview4' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field2' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field1' => 'grid' ),
'itemLocations' => array( 'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview3' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview4' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field18',
'simple_grid_field30',
'simple_grid_field39',
'grid_field' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4' ),
'grid_field_label' => array( 'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field19',
'simple_grid_field31',
'simple_grid_field40',
'simple_grid_field16',
'grid_field_label' ),
'image' => array( 'image' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'hr_id_qr_fieldheadercolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'hr_id_qr_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'hr_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'hr_id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'hr_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'hr_nit_contra_ta_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'user_from_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'user_from_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'id_cont_fk_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'id_cont_fk_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'nombrecont_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'nombrecont_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'sys_dep_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array( 'sys_dep_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'hr_anio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'hr_anio_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'hr_asunto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'hr_asunto_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array( 'sys_user_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array( 'sys_user_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'hr_valor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'hr_valor_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array( 'hr_fechaingreso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array( 'hr_fechaingreso_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c2',
'items' => array( 'image' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 6 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 6 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field5' ),
'field' => 'hr_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'hr_id',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field12' ),
'field' => 'hr_nit_contra_ta',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'hr_nit_contra_ta',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field31' ),
'field' => 'user_from',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'user_from',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field6' ),
'field' => 'id_cont_fk',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'id_cont_fk',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'nombrecont',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'nombrecont',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field40' ),
'field' => 'sys_dep',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'sys_dep',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field7' ),
'field' => 'hr_anio',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'hr_anio',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field13' ),
'field' => 'hr_asunto',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'hr_asunto',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field19' ),
'field' => 'sys_user',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'sys_user',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field14' ),
'field' => 'hr_valor',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'hr_valor',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field15' ),
'field' => 'hr_fechaingreso',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'hr_fechaingreso',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field16' ),
'field' => 'hr_id_qr',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'hr_id_qr',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field16' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 3 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'hr_id',
'type' => 'grid_field' ),
'simple_grid_field1' => array( 'field' => 'hr_id_qr',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'field' => 'id_cont_fk',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'field' => 'hr_anio',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'hr_nit_contra_ta',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'field' => 'hr_asunto',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'hr_valor',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'field' => 'hr_fechaingreso',
'type' => 'grid_field' ),
'simple_grid_field18' => array( 'field' => 'sys_user',
'type' => 'grid_field' ),
'simple_grid_field30' => array( 'field' => 'user_from',
'type' => 'grid_field' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'hoja_ruta_2020_files',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'hoja_ruta_2020_tracking',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'q_info_cont',
'items' => array(  ),
'popup' => false,
'pageId' => 'print1' ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 'hoja_ruta_ob',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'hoja_ruta_op',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'simple_grid_field39' => array( 'field' => 'sys_dep',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'hr_id' ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'id_cont_fk' ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'hr_anio' ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'hr_nit_contra_ta' ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'hr_asunto' ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'hr_valor' ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'hr_fechaingreso' ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'sys_user' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'user_from' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'sys_dep' ),
'simple_grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'hr_id_qr' ),
'image' => array( 'type' => 'image',
'imagePath' => 'Logo.png' ),
'grid_field' => array( 'field' => 'nombrecont',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'nombrecont' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>