<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'hr_id_fk',
'id_cont_fk',
'ob_num',
'ob_fecha',
'ob_anexo',
'ob_user',
'ob_fechauser',
'tercero_email_a',
'tercero_email_b' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'hr_id_fk' => array( 'import_field1' ),
'id_cont_fk' => array( 'import_field2' ),
'ob_num' => array( 'import_field3' ),
'ob_fecha' => array( 'import_field4' ),
'ob_anexo' => array( 'import_field5' ),
'ob_user' => array( 'import_field6' ),
'ob_fechauser' => array( 'import_field7' ),
'tercero_email_a' => array( 'import_field8' ),
'tercero_email_b' => array( 'import_field9' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'hr_id_fk',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'id_cont_fk',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'ob_num',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'ob_fecha',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'ob_anexo',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'ob_user',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'ob_fechauser',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'tercero_email_a',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'tercero_email_b',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>