<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'hoja_ruta_2020_files' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'hoja_ruta_2020_tracking' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'hoja_ruta_ob' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'hoja_ruta_op' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'q_info_cont' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'fields' => array( 'gridFields' => array( 'evento_type_id_fk',
'hr_anio',
'not_user',
'not_date',
'last_act_user',
'nombrecont',
'not_msg',
'not_mail',
'sys_user',
'hr_valor',
'hr_asunto',
'hr_nit_contra_ta',
'id_cont_fk',
'tercero_email_b',
'tercero_email_a',
'sys_dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'evento_type_id_fk' => array( 'integrated_edit_field28' ),
'hr_anio' => array( 'integrated_edit_field2' ),
'not_user' => array( 'integrated_edit_field23' ),
'not_date' => array( 'integrated_edit_field24' ),
'last_act_user' => array( 'integrated_edit_field3' ),
'nombrecont' => array( 'integrated_edit_field' ),
'not_msg' => array( 'integrated_edit_field26' ),
'not_mail' => array( 'integrated_edit_field25' ),
'sys_user' => array( 'integrated_edit_field17' ),
'hr_valor' => array( 'integrated_edit_field9' ),
'hr_asunto' => array( 'integrated_edit_field8' ),
'hr_nit_contra_ta' => array( 'integrated_edit_field7' ),
'id_cont_fk' => array( 'integrated_edit_field1' ),
'tercero_email_b' => array( 'integrated_edit_field35' ),
'tercero_email_a' => array( 'integrated_edit_field30' ),
'sys_dep' => array( 'integrated_edit_field4' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'section',
'tabs' ),
'section' => array( 'integrated_edit_field30',
'integrated_edit_field35',
'integrated_edit_field4',
'integrated_edit_field28',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field26',
'integrated_edit_field17',
'integrated_edit_field25' ),
'section2' => array( 'details_preview' ),
'section1' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field2',
'integrated_edit_field7',
'integrated_edit_field1' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'section' => 'grid',
'tabs' => 'grid',
'integrated_edit_field30' => 'section',
'integrated_edit_field35' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field28' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field26' => 'section',
'integrated_edit_field17' => 'section',
'integrated_edit_field25' => 'section',
'details_preview' => 'section2',
'integrated_edit_field' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field24' => 'section1',
'integrated_edit_field23' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field1' => 'section1' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field30' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field28' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field26' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field17' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field25' => array( 'location' => 'section',
'cellId' => 'c10' ),
'details_preview' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field24' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c9' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field28',
'integrated_edit_field2',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field17',
'integrated_edit_field9',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field1',
'integrated_edit_field35',
'integrated_edit_field30',
'integrated_edit_field4' ),
'tabs' => array( 'tabs' ),
'section' => array( 'section' ),
'details_preview' => array( 'details_preview' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c18' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c2' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c18',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c18' => array( 'model' => 'c3',
'items' => array( 'section',
'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ),
'useFullWidth' => true ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c6' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c6' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field28' => array( 'field' => 'evento_type_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'hr_anio',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'not_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'not_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'last_act_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'nombrecont',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'not_msg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'not_msg',
'table' => 'hoja_ruta_2020_pn',
'type' => 3 ),
'tooltip' => array( 'field' => 'not_msg',
'table' => null,
'type' => 4 ),
'updateOnEdit' => false ),
'integrated_edit_field25' => array( 'field' => 'not_mail',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field17' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'hr_valor',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'hr_valor',
'table' => 'hoja_ruta_2020_pn',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'hr_asunto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Gestionar solicitud de pago',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ) ),
'integrated_edit_field7' => array( 'field' => 'hr_nit_contra_ta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'id_cont_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field35' => array( 'field' => 'tercero_email_b',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'tercero_email_a',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => '+ Información del contrato',
'type' => 0 ),
'location' => 'section2',
'initiallyClosed' => true ),
'integrated_edit_field4' => array( 'field' => 'sys_dep',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'sys_dep',
'table' => 'hoja_ruta_2020_pn1',
'type' => 3 ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'q_info_cont',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>