<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'numcontrato' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'PLAZO' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'documento_id' => array( 'totalsType' => '' ),
'nombres' => array( 'totalsType' => '' ),
'apellidos' => array( 'totalsType' => '' ),
'nombresupfull' => array( 'totalsType' => '' ),
'cargo_id' => array( 'totalsType' => '' ),
'dependencia_id' => array( 'totalsType' => '' ),
'sup_fechanot' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'sup_status' => array( 'totalsType' => '' ),
'idusrglobal_fk' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'nombre_cargo' => array( 'totalsType' => '' ),
'nombre_dependencia' => array( 'totalsType' => '' ),
'id_depto_superior' => array( 'totalsType' => '' ),
'Departamento_superior' => array( 'totalsType' => '' ),
'cont_numpoliza' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ),
'cont_modifica' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cont_nit_contra_ta',
'contractor_nombresfull',
'cont_estado',
'numcontrato',
'cont_ano',
'documento_id',
'nombres',
'apellidos',
'cargo_id',
'dependencia_id',
'PLAZO',
'nombresupfull',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'sup_status',
'Username',
'cont_modifica',
'cont_cesion',
'cont_munejec',
'cont_fechaapertura',
'cont_fecha_aprobgarantia',
'cont_secop_proceso',
'cont_numpoliza',
'Departamento_superior',
'id_depto_superior',
'nombre_dependencia',
'nombre_cargo',
'ctb_tipo_nombre',
'cont_plazo',
'cont_obligaciones',
'cont_objeto',
'cont_causalc',
'cont_tipopre',
'cont_tipo_rubro',
'cont_unspsc',
'numregistro',
'prenumero',
'nombresupfull',
'PLAZO',
'id_cont',
'sup_mailnot',
'sup_fechanot',
'cont_secop_enlace',
'cont_valormensual',
'cont_valorinicial',
'cont_periodicidad',
'cont_fechafinal',
'cont_fecha_inicio',
'cont_catalogo_presupuestal',
'cont_codrubro',
'contractor_email_mincit',
'contractor_email',
'contractor_nombresfull',
'contractor_lname',
'contractor_name',
'idusrglobal_fk',
'dependencia_id',
'cargo_id',
'apellidos',
'nombres',
'documento_id',
'cont_ano',
'contnumero',
'pre_contnumero',
'numcontrato',
'cont_estado',
'cont_nit_contra_ta' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'PLAZO',
'nombresupfull',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username' ),
'inlineEditFields' => array( 'PLAZO',
'nombresupfull',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username' ),
'fieldItems' => array( 'cont_nit_contra_ta' => array( 'simple_grid_field1',
'simple_grid_field34' ),
'contractor_nombresfull' => array( 'simple_grid_field26',
'simple_grid_field35' ),
'cont_estado' => array( 'simple_grid_field2',
'simple_grid_field36' ),
'numcontrato' => array( 'simple_grid_field3',
'simple_grid_field37' ),
'cont_ano' => array( 'simple_grid_field6',
'simple_grid_field38' ),
'documento_id' => array( 'simple_grid_field15',
'simple_grid_field39' ),
'nombres' => array( 'simple_grid_field16',
'simple_grid_field40' ),
'apellidos' => array( 'simple_grid_field17',
'simple_grid_field41' ),
'cargo_id' => array( 'simple_grid_field18',
'simple_grid_field42' ),
'dependencia_id' => array( 'simple_grid_field19',
'simple_grid_field43' ),
'PLAZO' => array( 'simple_grid_field',
'simple_grid_field44' ),
'nombresupfull' => array( 'simple_grid_field4',
'simple_grid_field45' ),
'prenumero' => array( 'simple_grid_field5',
'simple_grid_field46' ),
'numregistro' => array( 'simple_grid_field7',
'simple_grid_field47' ),
'cont_unspsc' => array( 'simple_grid_field8',
'simple_grid_field48' ),
'cont_tipo_rubro' => array( 'simple_grid_field9',
'simple_grid_field49' ),
'cont_tipopre' => array( 'simple_grid_field10',
'simple_grid_field50' ),
'cont_causalc' => array( 'simple_grid_field11',
'simple_grid_field51' ),
'cont_objeto' => array( 'simple_grid_field12',
'simple_grid_field52' ),
'cont_obligaciones' => array( 'simple_grid_field13',
'simple_grid_field53' ),
'cont_plazo' => array( 'simple_grid_field14',
'simple_grid_field54' ),
'ctb_tipo_nombre' => array( 'simple_grid_field20',
'simple_grid_field55' ),
'nombre_cargo' => array( 'simple_grid_field21',
'simple_grid_field56' ),
'nombre_dependencia' => array( 'simple_grid_field22',
'simple_grid_field57' ),
'id_depto_superior' => array( 'simple_grid_field23',
'simple_grid_field58' ),
'Departamento_superior' => array( 'simple_grid_field24',
'simple_grid_field59' ),
'cont_numpoliza' => array( 'simple_grid_field25',
'simple_grid_field60' ),
'cont_secop_proceso' => array( 'simple_grid_field27',
'simple_grid_field61' ),
'cont_fecha_aprobgarantia' => array( 'simple_grid_field28',
'simple_grid_field62' ),
'cont_fechaapertura' => array( 'simple_grid_field29',
'simple_grid_field63' ),
'cont_munejec' => array( 'simple_grid_field30',
'simple_grid_field64' ),
'cont_cesion' => array( 'simple_grid_field31',
'simple_grid_field65' ),
'cont_modifica' => array( 'simple_grid_field32',
'simple_grid_field66' ),
'Username' => array( 'simple_grid_field33',
'simple_grid_field67' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field34',
'simple_grid_field1',
'simple_grid_field35',
'simple_grid_field26',
'simple_grid_field36',
'simple_grid_field2',
'simple_grid_field37',
'simple_grid_field3',
'simple_grid_field38',
'simple_grid_field6',
'simple_grid_field39',
'simple_grid_field15',
'simple_grid_field40',
'simple_grid_field16',
'simple_grid_field41',
'simple_grid_field17',
'simple_grid_field42',
'simple_grid_field18',
'simple_grid_field43',
'simple_grid_field19',
'simple_grid_field44',
'simple_grid_field',
'simple_grid_field45',
'simple_grid_field4',
'simple_grid_field46',
'simple_grid_field5',
'simple_grid_field47',
'simple_grid_field7',
'simple_grid_field48',
'simple_grid_field8',
'simple_grid_field49',
'simple_grid_field9',
'simple_grid_field50',
'simple_grid_field10',
'simple_grid_field51',
'simple_grid_field11',
'simple_grid_field52',
'simple_grid_field12',
'simple_grid_field53',
'simple_grid_field13',
'simple_grid_field54',
'simple_grid_field14',
'simple_grid_field55',
'simple_grid_field20',
'simple_grid_field56',
'simple_grid_field21',
'simple_grid_field57',
'simple_grid_field22',
'simple_grid_field58',
'simple_grid_field23',
'simple_grid_field59',
'simple_grid_field24',
'simple_grid_field60',
'simple_grid_field25',
'simple_grid_field61',
'simple_grid_field27',
'simple_grid_field62',
'simple_grid_field28',
'simple_grid_field63',
'simple_grid_field29',
'simple_grid_field64',
'simple_grid_field30',
'simple_grid_field65',
'simple_grid_field31',
'simple_grid_field66',
'simple_grid_field32',
'simple_grid_field67',
'simple_grid_field33' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field34' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field33' => 'grid' ),
'itemLocations' => array( 'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'list_options' => array( 'list_options' ),
'-' => array( '-2',
'-',
'-1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'show_search_panel' => array( 'show_search_panel' ),
'search_panel_field' => array( 'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52' ),
'search_panel' => array( 'search_panel' ),
'logo' => array( 'logo1' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field26',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field6',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33' ),
'grid_field_label' => array( 'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'cont_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'cont_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'numcontrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'documento_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'nombres_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'apellidos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'cargo_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'dependencia_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'PLAZO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'nombresupfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'prenumero_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'numregistro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'cont_unspsc_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'cont_tipo_rubro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'cont_tipopre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'cont_causalc_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'cont_obligaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'cont_plazo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'ctb_tipo_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'nombre_cargo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'nombre_dependencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'id_depto_superior_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'Departamento_superior_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'cont_numpoliza_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'cont_secop_proceso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'cont_fechaapertura_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'cont_munejec_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'cont_cesion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'cont_modifica_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'Username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cont_nit_contra_ta_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'cont_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'numcontrato_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'documento_id_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'nombres_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'apellidos_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'cargo_id_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'dependencia_id_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'PLAZO_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'nombresupfull_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'prenumero_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'numregistro_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'cont_unspsc_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'cont_tipo_rubro_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'cont_tipopre_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'cont_causalc_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'cont_obligaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'cont_plazo_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'ctb_tipo_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'nombre_cargo_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'nombre_dependencia_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'id_depto_superior_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'Departamento_superior_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'cont_numpoliza_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'cont_secop_proceso_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'cont_fechaapertura_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'cont_munejec_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'cont_cesion_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'cont_modifica_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'Username_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 34,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'documento_id',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'documento_id',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'nombres',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'nombres',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'apellidos',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'apellidos',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'cargo_id',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'cargo_id',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'dependencia_id',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'dependencia_id',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'PLAZO',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'PLAZO',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'nombresupfull',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'nombresupfull',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'cont_tipopre',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'cont_tipopre',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'cont_causalc',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'cont_causalc',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'cont_obligaciones',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'cont_obligaciones',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'cont_plazo',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'cont_plazo',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'nombre_cargo',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'nombre_cargo',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'nombre_dependencia',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'nombre_dependencia',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'id_depto_superior',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'id_depto_superior',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'Departamento_superior',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'Departamento_superior',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'cont_numpoliza',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'cont_numpoliza',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'cont_fechaapertura',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'cont_fechaapertura',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'Username',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'Username',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'-2' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'search_panel_field28' => array( 'field' => 'contractor_email_mincit',
'type' => 'search_panel_field' ),
'search_panel_field27' => array( 'field' => 'contractor_email',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'contractor_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'contractor_lname',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'contractor_name',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'idusrglobal_fk',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'dependencia_id',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field18' => array( 'field' => 'cargo_id',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field17' => array( 'field' => 'apellidos',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'nombres',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'documento_id',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'cont_ano',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'contnumero',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'pre_contnumero',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'numcontrato',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'cont_estado',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'search_panel_field' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field22',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field',
'search_panel_field21',
'search_panel_field20',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'logo1' => array( 'type' => 'logo' ),
'search_panel_field7' => array( 'field' => 'cont_codrubro',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'cont_fecha_inicio',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'cont_fechafinal',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'cont_periodicidad',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'cont_valorinicial',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'cont_valormensual',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'cont_secop_enlace',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'sup_fechanot',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'sup_mailnot',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'sup_status',
'type' => 'search_panel_field' ),
'search_panel_field' => array( 'field' => 'id_cont',
'type' => 'search_panel_field' ),
'search_panel_field29' => array( 'field' => 'PLAZO',
'type' => 'search_panel_field',
'required' => false ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'search_panel_field30' => array( 'field' => 'nombresupfull',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field31' => array( 'field' => 'prenumero',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field32' => array( 'field' => 'numregistro',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field33' => array( 'field' => 'cont_unspsc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field34' => array( 'field' => 'cont_tipo_rubro',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field35' => array( 'field' => 'cont_tipopre',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field36' => array( 'field' => 'cont_causalc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field37' => array( 'field' => 'cont_objeto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field38' => array( 'field' => 'cont_obligaciones',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'cont_plazo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field41' => array( 'field' => 'nombre_cargo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field42' => array( 'field' => 'nombre_dependencia',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field43' => array( 'field' => 'id_depto_superior',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field44' => array( 'field' => 'Departamento_superior',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field45' => array( 'field' => 'cont_numpoliza',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field46' => array( 'field' => 'cont_secop_proceso',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field47' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'cont_fechaapertura',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'cont_munejec',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'cont_cesion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field51' => array( 'field' => 'cont_modifica',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'Username',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_ta' ),
'simple_grid_field26' => array( 'field' => 'contractor_nombresfull',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'contractor_nombresfull' ),
'simple_grid_field2' => array( 'field' => 'cont_estado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'cont_estado' ),
'simple_grid_field3' => array( 'field' => 'numcontrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'numcontrato' ),
'simple_grid_field6' => array( 'field' => 'cont_ano',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'simple_grid_field15' => array( 'field' => 'documento_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'documento_id' ),
'simple_grid_field16' => array( 'field' => 'nombres',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'nombres' ),
'simple_grid_field17' => array( 'field' => 'apellidos',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'apellidos' ),
'simple_grid_field18' => array( 'field' => 'cargo_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'cargo_id' ),
'simple_grid_field19' => array( 'field' => 'dependencia_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'dependencia_id' ),
'simple_grid_field' => array( 'field' => 'PLAZO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'PLAZO' ),
'simple_grid_field4' => array( 'field' => 'nombresupfull',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'nombresupfull' ),
'simple_grid_field5' => array( 'field' => 'prenumero',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'prenumero' ),
'simple_grid_field7' => array( 'field' => 'numregistro',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'numregistro' ),
'simple_grid_field8' => array( 'field' => 'cont_unspsc',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'cont_unspsc' ),
'simple_grid_field9' => array( 'field' => 'cont_tipo_rubro',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipo_rubro' ),
'simple_grid_field10' => array( 'field' => 'cont_tipopre',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipopre' ),
'simple_grid_field11' => array( 'field' => 'cont_causalc',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'cont_causalc' ),
'simple_grid_field12' => array( 'field' => 'cont_objeto',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'simple_grid_field13' => array( 'field' => 'cont_obligaciones',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'cont_obligaciones' ),
'simple_grid_field14' => array( 'field' => 'cont_plazo',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'cont_plazo' ),
'simple_grid_field20' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'ctb_tipo_nombre' ),
'simple_grid_field21' => array( 'field' => 'nombre_cargo',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'nombre_cargo' ),
'simple_grid_field22' => array( 'field' => 'nombre_dependencia',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'nombre_dependencia' ),
'simple_grid_field23' => array( 'field' => 'id_depto_superior',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'id_depto_superior' ),
'simple_grid_field24' => array( 'field' => 'Departamento_superior',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'Departamento_superior' ),
'simple_grid_field25' => array( 'field' => 'cont_numpoliza',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'cont_numpoliza' ),
'simple_grid_field27' => array( 'field' => 'cont_secop_proceso',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_proceso' ),
'simple_grid_field28' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_aprobgarantia' ),
'simple_grid_field29' => array( 'field' => 'cont_fechaapertura',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechaapertura' ),
'simple_grid_field30' => array( 'field' => 'cont_munejec',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'cont_munejec' ),
'simple_grid_field31' => array( 'field' => 'cont_cesion',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'cont_cesion' ),
'simple_grid_field32' => array( 'field' => 'cont_modifica',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'cont_modifica' ),
'simple_grid_field33' => array( 'field' => 'Username',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'Username' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>