<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'master' => array( 'hoja_ruta_2020_pn1' => array( 'preview' => false ) ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'numcontrato' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'PLAZO' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'documento_id' => array( 'totalsType' => '' ),
'nombres' => array( 'totalsType' => '' ),
'apellidos' => array( 'totalsType' => '' ),
'nombresupfull' => array( 'totalsType' => '' ),
'cargo_id' => array( 'totalsType' => '' ),
'dependencia_id' => array( 'totalsType' => '' ),
'sup_fechanot' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'sup_status' => array( 'totalsType' => '' ),
'idusrglobal_fk' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'nombre_cargo' => array( 'totalsType' => '' ),
'nombre_dependencia' => array( 'totalsType' => '' ),
'id_depto_superior' => array( 'totalsType' => '' ),
'Departamento_superior' => array( 'totalsType' => '' ),
'cont_numpoliza' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ),
'cont_modifica' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cont_cesion',
'cont_modifica' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_cesion' => array( 'simple_grid_field',
'simple_grid_field2' ),
'cont_modifica' => array( 'simple_grid_field1',
'simple_grid_field3' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field2',
'simple_grid_field',
'simple_grid_field3',
'simple_grid_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'simple_grid_field2' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field1' => 'grid' ),
'itemLocations' => array( 'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1' ),
'grid_field_label' => array( 'simple_grid_field2',
'simple_grid_field3' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'cont_cesion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'cont_modifica_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cont_cesion_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'cont_modifica_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print1',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'cont_cesion',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'cont_cesion' ),
'simple_grid_field1' => array( 'field' => 'cont_modifica',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'cont_modifica' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>