<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'hoja_ruta_2020_pn1' => array( 'preview' => true ),
'hoja_ruta_2020_pn2' => array( 'preview' => true ),
'hoja_ruta_2020_pn' => array( 'preview' => true ),
'hoja_ruta_2020_pn0' => array( 'preview' => true ),
'hoja_ruta_2020_pnc1' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'numcontrato' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'PLAZO' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'documento_id' => array( 'totalsType' => '' ),
'nombres' => array( 'totalsType' => '' ),
'apellidos' => array( 'totalsType' => '' ),
'nombresupfull' => array( 'totalsType' => '' ),
'cargo_id' => array( 'totalsType' => '' ),
'dependencia_id' => array( 'totalsType' => '' ),
'sup_fechanot' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'sup_status' => array( 'totalsType' => '' ),
'idusrglobal_fk' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'nombre_cargo' => array( 'totalsType' => '' ),
'nombre_dependencia' => array( 'totalsType' => '' ),
'id_depto_superior' => array( 'totalsType' => '' ),
'Departamento_superior' => array( 'totalsType' => '' ),
'cont_numpoliza' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ),
'cont_modifica' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'contractor_nombresfull',
'dependencia_id',
'cargo_id',
'apellidos',
'nombres',
'documento_id',
'cont_ano',
'numcontrato',
'cont_estado',
'cont_nit_contra_ta',
'cont_secop_enlace',
'PLAZO',
'nombresupfull',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'sup_status',
'Username',
'cont_modifica',
'cont_cesion',
'cont_munejec',
'cont_fechaapertura',
'cont_fecha_aprobgarantia',
'cont_secop_proceso',
'cont_numpoliza',
'Departamento_superior',
'id_depto_superior',
'nombre_dependencia',
'nombre_cargo',
'ctb_tipo_nombre',
'cont_plazo',
'cont_obligaciones',
'cont_objeto',
'cont_causalc',
'cont_tipopre',
'cont_tipo_rubro',
'cont_unspsc',
'numregistro',
'prenumero',
'nombresupfull',
'PLAZO',
'id_cont',
'sup_mailnot',
'sup_fechanot',
'cont_secop_enlace',
'cont_valormensual',
'cont_valorinicial',
'cont_periodicidad',
'cont_fechafinal',
'cont_fecha_inicio',
'cont_catalogo_presupuestal',
'cont_codrubro',
'contractor_email_mincit',
'contractor_email',
'contractor_nombresfull',
'contractor_lname',
'contractor_name',
'idusrglobal_fk',
'dependencia_id',
'cargo_id',
'apellidos',
'nombres',
'documento_id',
'cont_ano',
'contnumero',
'pre_contnumero',
'numcontrato',
'cont_estado',
'cont_nit_contra_ta' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'PLAZO',
'nombresupfull',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username' ),
'inlineEditFields' => array( 'PLAZO',
'nombresupfull',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username' ),
'fieldItems' => array( 'contractor_nombresfull' => array( 'simple_grid_field26',
'simple_grid_field27' ),
'dependencia_id' => array( 'simple_grid_field19',
'simple_grid_field24' ),
'cargo_id' => array( 'simple_grid_field18',
'simple_grid_field23' ),
'apellidos' => array( 'simple_grid_field17',
'simple_grid_field22' ),
'nombres' => array( 'simple_grid_field16',
'simple_grid_field21' ),
'documento_id' => array( 'simple_grid_field15',
'simple_grid_field20' ),
'cont_ano' => array( 'simple_grid_field6',
'simple_grid_field7' ),
'numcontrato' => array( 'simple_grid_field3',
'simple_grid_field5' ),
'cont_estado' => array( 'simple_grid_field2',
'simple_grid_field4' ),
'cont_nit_contra_ta' => array( 'simple_grid_field1',
'simple_grid_field' ),
'cont_secop_enlace' => array( 'grid_field',
'grid_field_label' ),
'PLAZO' => array( 'grid_field1',
'grid_field_label1' ),
'nombresupfull' => array( 'grid_field2',
'grid_field_label2' ),
'prenumero' => array( 'grid_field3',
'grid_field_label3' ),
'numregistro' => array( 'grid_field4',
'grid_field_label4' ),
'cont_unspsc' => array( 'grid_field5',
'grid_field_label5' ),
'cont_tipo_rubro' => array( 'grid_field6',
'grid_field_label6' ),
'cont_tipopre' => array( 'grid_field7',
'grid_field_label7' ),
'cont_causalc' => array( 'grid_field8',
'grid_field_label8' ),
'cont_objeto' => array( 'grid_field9',
'grid_field_label9' ),
'cont_obligaciones' => array( 'grid_field10',
'grid_field_label10' ),
'cont_plazo' => array( 'grid_field11',
'grid_field_label11' ),
'ctb_tipo_nombre' => array( 'grid_field12',
'grid_field_label12' ),
'nombre_cargo' => array( 'grid_field13',
'grid_field_label13' ),
'nombre_dependencia' => array( 'grid_field14',
'grid_field_label14' ),
'id_depto_superior' => array( 'grid_field15',
'grid_field_label15' ),
'Departamento_superior' => array( 'grid_field16',
'grid_field_label16' ),
'cont_numpoliza' => array( 'grid_field17',
'grid_field_label17' ),
'cont_secop_proceso' => array( 'grid_field18',
'grid_field_label18' ),
'cont_fecha_aprobgarantia' => array( 'grid_field19',
'grid_field_label19' ),
'cont_fechaapertura' => array( 'grid_field20',
'grid_field_label20' ),
'cont_munejec' => array( 'grid_field21',
'grid_field_label21' ),
'cont_cesion' => array( 'grid_field22',
'grid_field_label22' ),
'cont_modifica' => array( 'grid_field23',
'grid_field_label23' ),
'Username' => array( 'grid_field24',
'grid_field_label24' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'inline_add',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field20',
'simple_grid_field15',
'simple_grid_field27',
'simple_grid_field26',
'simple_grid_field21',
'simple_grid_field16',
'simple_grid_field4',
'simple_grid_field2',
'simple_grid_field22',
'simple_grid_field17',
'simple_grid_field5',
'simple_grid_field3',
'simple_grid_field23',
'simple_grid_field18',
'simple_grid_field7',
'simple_grid_field6',
'simple_grid_field24',
'simple_grid_field19',
'grid_checkbox',
'grid_inline_cancel',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label11',
'grid_field11',
'grid_field_label12',
'grid_field12',
'grid_field_label13',
'grid_field13',
'grid_field_label14',
'grid_field14',
'grid_field_label15',
'grid_field15',
'grid_field_label16',
'grid_field16',
'grid_field_label17',
'grid_field17',
'grid_field_label18',
'grid_field18',
'grid_field_label19',
'grid_field19',
'grid_field_label20',
'grid_field20',
'grid_field_label21',
'grid_field21',
'grid_field_label22',
'grid_field22',
'grid_field_label23',
'grid_field23',
'grid_field_label24',
'grid_field24' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'inline_add' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field19' => 'grid',
'grid_checkbox' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid',
'grid_field_label14' => 'grid',
'grid_field14' => 'grid',
'grid_field_label15' => 'grid',
'grid_field15' => 'grid',
'grid_field_label16' => 'grid',
'grid_field16' => 'grid',
'grid_field_label17' => 'grid',
'grid_field17' => 'grid',
'grid_field_label18' => 'grid',
'grid_field18' => 'grid',
'grid_field_label19' => 'grid',
'grid_field19' => 'grid',
'grid_field_label20' => 'grid',
'grid_field20' => 'grid',
'grid_field_label21' => 'grid',
'grid_field21' => 'grid',
'grid_field_label22' => 'grid',
'grid_field22' => 'grid',
'grid_field_label23' => 'grid',
'grid_field23' => 'grid',
'grid_field_label24' => 'grid',
'grid_field24' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_label13' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_label14' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'cell_label17' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_label19' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'cell_label20' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'cell_label21' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'cell_label22' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'cell_label23' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'grid_field_label14' => array( 'location' => 'grid',
'cellId' => 'cell_label24' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'grid_field_label15' => array( 'location' => 'grid',
'cellId' => 'cell_label25' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'grid_field_label16' => array( 'location' => 'grid',
'cellId' => 'cell_label26' ),
'grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'grid_field_label17' => array( 'location' => 'grid',
'cellId' => 'cell_label27' ),
'grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'grid_field_label18' => array( 'location' => 'grid',
'cellId' => 'cell_label28' ),
'grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'grid_field_label19' => array( 'location' => 'grid',
'cellId' => 'cell_label29' ),
'grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'grid_field_label20' => array( 'location' => 'grid',
'cellId' => 'cell_label30' ),
'grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'grid_field_label21' => array( 'location' => 'grid',
'cellId' => 'cell_label31' ),
'grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'grid_field_label22' => array( 'location' => 'grid',
'cellId' => 'cell_label32' ),
'grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'grid_field_label23' => array( 'location' => 'grid',
'cellId' => 'cell_label33' ),
'grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'grid_field_label24' => array( 'location' => 'grid',
'cellId' => 'cell_label34' ),
'grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field26',
'simple_grid_field19',
'simple_grid_field18',
'simple_grid_field17',
'simple_grid_field16',
'simple_grid_field15',
'simple_grid_field6',
'simple_grid_field3',
'simple_grid_field2',
'simple_grid_field1',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field10',
'grid_field11',
'grid_field12',
'grid_field13',
'grid_field14',
'grid_field15',
'grid_field16',
'grid_field17',
'grid_field18',
'grid_field19',
'grid_field20',
'grid_field21',
'grid_field22',
'grid_field23',
'grid_field24' ),
'-' => array( '-2',
'-',
'-1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'show_search_panel' => array( 'show_search_panel' ),
'search_panel_field' => array( 'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52' ),
'search_panel' => array( 'search_panel' ),
'logo' => array( 'logo1' ),
'master_info' => array( 'master_info' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field27',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field7',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label9',
'grid_field_label10',
'grid_field_label11',
'grid_field_label12',
'grid_field_label13',
'grid_field_label14',
'grid_field_label15',
'grid_field_label16',
'grid_field_label17',
'grid_field_label18',
'grid_field_label19',
'grid_field_label20',
'grid_field_label21',
'grid_field_label22',
'grid_field_label23',
'grid_field_label24' ),
'advsearch_link' => array( 'advsearch_link' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column',
'inline_cancel' ),
'items' => array( 'grid_checkbox',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cont_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'cont_nit_contra_ta_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'documento_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'documento_id_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'contractor_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'contractor_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'nombres_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'nombres_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'cont_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'cont_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'apellidos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'apellidos_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'numcontrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'numcontrato_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cargo_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'cargo_id_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'dependencia_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'dependencia_id_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 6 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'PLAZO_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'PLAZO_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'nombresupfull_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'nombresupfull_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'prenumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array( 'prenumero_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array( 'numregistro_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array( 'numregistro_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'cont_unspsc_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'cont_unspsc_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array( 'cont_tipo_rubro_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'cont_tipo_rubro_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'cont_tipopre_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array( 'cont_tipopre_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array( 'cont_causalc_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array( 'cont_causalc_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label20' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array( 'cont_obligaciones_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array( 'cont_obligaciones_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label21' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'cont_plazo_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array( 'cont_plazo_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label22' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array( 'ctb_tipo_nombre_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array( 'ctb_tipo_nombre_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label23' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'nombre_cargo_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array( 'nombre_cargo_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array( 'nombre_dependencia_fieldheadercolumn' ),
'items' => array( 'grid_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array( 'nombre_dependencia_fieldcolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label25' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array( 'id_depto_superior_fieldheadercolumn' ),
'items' => array( 'grid_field_label15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array( 'id_depto_superior_fieldcolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label26' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array( 'Departamento_superior_fieldheadercolumn' ),
'items' => array( 'grid_field_label16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 3 ),
'rows' => array( 14 ),
'tags' => array( 'Departamento_superior_fieldcolumn' ),
'items' => array( 'grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label27' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array( 'cont_numpoliza_fieldheadercolumn' ),
'items' => array( 'grid_field_label17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array( 'cont_numpoliza_fieldcolumn' ),
'items' => array( 'grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label28' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array( 'cont_secop_proceso_fieldheadercolumn' ),
'items' => array( 'grid_field_label18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 3 ),
'rows' => array( 15 ),
'tags' => array( 'cont_secop_proceso_fieldcolumn' ),
'items' => array( 'grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label29' => array( 'cols' => array( 0 ),
'rows' => array( 16 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldheadercolumn' ),
'items' => array( 'grid_field_label19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 1 ),
'rows' => array( 16 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldcolumn' ),
'items' => array( 'grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label30' => array( 'cols' => array( 2 ),
'rows' => array( 16 ),
'tags' => array( 'cont_fechaapertura_fieldheadercolumn' ),
'items' => array( 'grid_field_label20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 3 ),
'rows' => array( 16 ),
'tags' => array( 'cont_fechaapertura_fieldcolumn' ),
'items' => array( 'grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label31' => array( 'cols' => array( 0 ),
'rows' => array( 17 ),
'tags' => array( 'cont_munejec_fieldheadercolumn' ),
'items' => array( 'grid_field_label21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 1 ),
'rows' => array( 17 ),
'tags' => array( 'cont_munejec_fieldcolumn' ),
'items' => array( 'grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label32' => array( 'cols' => array( 2 ),
'rows' => array( 17 ),
'tags' => array( 'cont_cesion_fieldheadercolumn' ),
'items' => array( 'grid_field_label22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 3 ),
'rows' => array( 17 ),
'tags' => array( 'cont_cesion_fieldcolumn' ),
'items' => array( 'grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label33' => array( 'cols' => array( 0 ),
'rows' => array( 18 ),
'tags' => array( 'cont_modifica_fieldheadercolumn' ),
'items' => array( 'grid_field_label23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 1 ),
'rows' => array( 18 ),
'tags' => array( 'cont_modifica_fieldcolumn' ),
'items' => array( 'grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label34' => array( 'cols' => array( 2 ),
'rows' => array( 18 ),
'tags' => array( 'Username_fieldheadercolumn' ),
'items' => array( 'grid_field_label24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 3 ),
'rows' => array( 18 ),
'tags' => array( 'Username_fieldcolumn' ),
'items' => array( 'grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 20 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10',
'colspan' => 3 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field16' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_field18' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_label20' ),
array( 'cell' => 'cell_field20' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label21' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_label22' ),
array( 'cell' => 'cell_field22' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label23' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_label24' ),
array( 'cell' => 'cell_field24' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label25' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_label26' ),
array( 'cell' => 'cell_field26' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label27' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_label28' ),
array( 'cell' => 'cell_field28' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label29' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_label30' ),
array( 'cell' => 'cell_field30' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label31' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_label32' ),
array( 'cell' => 'cell_field32' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label33' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_label34' ),
array( 'cell' => 'cell_field34' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field20' ),
'field' => 'documento_id',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'documento_id',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field27' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field21' ),
'field' => 'nombres',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'nombres',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field4' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field22' ),
'field' => 'apellidos',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'apellidos',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field5' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field23' ),
'field' => 'cargo_id',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'cargo_id',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field7' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field24' ),
'field' => 'dependencia_id',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'dependencia_id',
'columnName' => 'field' ),
'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_checkbox',
'grid_inline_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'PLAZO',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'PLAZO',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'nombresupfull',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'nombresupfull',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label3' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label4' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label5' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label6' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label7' ),
'field' => 'cont_tipopre',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'cont_tipopre',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label8' ),
'field' => 'cont_causalc',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'cont_causalc',
'columnName' => 'field' ),
'cell_label19' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label9' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_label20' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label10' ),
'field' => 'cont_obligaciones',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'cont_obligaciones',
'columnName' => 'field' ),
'cell_label21' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label11' ),
'field' => 'cont_plazo',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'cont_plazo',
'columnName' => 'field' ),
'cell_label22' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label12' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_label23' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label13' ),
'field' => 'nombre_cargo',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'nombre_cargo',
'columnName' => 'field' ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label14' ),
'field' => 'nombre_dependencia',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'grid_field14' ),
'field' => 'nombre_dependencia',
'columnName' => 'field' ),
'cell_label25' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label15' ),
'field' => 'id_depto_superior',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'grid_field15' ),
'field' => 'id_depto_superior',
'columnName' => 'field' ),
'cell_label26' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label16' ),
'field' => 'Departamento_superior',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'grid_field16' ),
'field' => 'Departamento_superior',
'columnName' => 'field' ),
'cell_label27' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label17' ),
'field' => 'cont_numpoliza',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'grid_field17' ),
'field' => 'cont_numpoliza',
'columnName' => 'field' ),
'cell_label28' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label18' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'grid_field18' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_label29' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label19' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'grid_field19' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_label30' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label20' ),
'field' => 'cont_fechaapertura',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'grid_field20' ),
'field' => 'cont_fechaapertura',
'columnName' => 'field' ),
'cell_label31' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label21' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'grid_field21' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_label32' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label22' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'grid_field22' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_label33' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label23' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'grid_field23' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_label34' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label24' ),
'field' => 'Username',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'grid_field24' ),
'field' => 'Username',
'columnName' => 'field' ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'buildType' => 2,
'columnCount' => 2 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'simple_grid_field26' => array( 'field' => 'contractor_nombresfull',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field19' => array( 'field' => 'dependencia_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field18' => array( 'field' => 'cargo_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field17' => array( 'field' => 'apellidos',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field16' => array( 'field' => 'nombres',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field15' => array( 'field' => 'documento_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'field' => 'cont_ano',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field3' => array( 'field' => 'numcontrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field2' => array( 'field' => 'cont_estado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'-2' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'search_panel_field28' => array( 'field' => 'contractor_email_mincit',
'type' => 'search_panel_field' ),
'search_panel_field27' => array( 'field' => 'contractor_email',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'contractor_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'contractor_lname',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'contractor_name',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'idusrglobal_fk',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'dependencia_id',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field18' => array( 'field' => 'cargo_id',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field17' => array( 'field' => 'apellidos',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'nombres',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'documento_id',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'cont_ano',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'contnumero',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'pre_contnumero',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'numcontrato',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'cont_estado',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'search_panel_field' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field22',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field',
'search_panel_field21',
'search_panel_field20',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'logo1' => array( 'type' => 'logo' ),
'search_panel_field7' => array( 'field' => 'cont_codrubro',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'cont_fecha_inicio',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'cont_fechafinal',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'cont_periodicidad',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'cont_valorinicial',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'cont_valormensual',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'cont_secop_enlace',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field20' => array( 'field' => 'sup_fechanot',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'sup_mailnot',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'sup_status',
'type' => 'search_panel_field' ),
'search_panel_field' => array( 'field' => 'id_cont',
'type' => 'search_panel_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'hoja_ruta_2020_pn1' => 'true',
'hoja_ruta_2020_pn2' => 'true',
'hoja_ruta_2020_pn' => 'true',
'hoja_ruta_2020_pn0' => 'true',
'hoja_ruta_2020_pnc1' => 'true' ) ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_ta' ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'contractor_nombresfull' ),
'simple_grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'cont_estado' ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'numcontrato' ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'documento_id' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'nombres' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'apellidos' ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'cargo_id' ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'dependencia_id' ),
'grid_field' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace' ),
'grid_field1' => array( 'field' => 'PLAZO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'PLAZO' ),
'search_panel_field29' => array( 'field' => 'PLAZO',
'type' => 'search_panel_field',
'required' => false ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'grid_field2' => array( 'field' => 'nombresupfull',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'nombresupfull' ),
'search_panel_field30' => array( 'field' => 'nombresupfull',
'type' => 'search_panel_field',
'required' => false ),
'grid_field3' => array( 'field' => 'prenumero',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'prenumero' ),
'search_panel_field31' => array( 'field' => 'prenumero',
'type' => 'search_panel_field',
'required' => false ),
'grid_field4' => array( 'field' => 'numregistro',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'numregistro' ),
'search_panel_field32' => array( 'field' => 'numregistro',
'type' => 'search_panel_field',
'required' => false ),
'grid_field5' => array( 'field' => 'cont_unspsc',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'cont_unspsc' ),
'search_panel_field33' => array( 'field' => 'cont_unspsc',
'type' => 'search_panel_field',
'required' => false ),
'grid_field6' => array( 'field' => 'cont_tipo_rubro',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipo_rubro' ),
'search_panel_field34' => array( 'field' => 'cont_tipo_rubro',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field7' => array( 'field' => 'cont_tipopre',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipopre' ),
'search_panel_field35' => array( 'field' => 'cont_tipopre',
'type' => 'search_panel_field',
'required' => false ),
'grid_field8' => array( 'field' => 'cont_causalc',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'cont_causalc' ),
'search_panel_field36' => array( 'field' => 'cont_causalc',
'type' => 'search_panel_field',
'required' => false ),
'grid_field9' => array( 'field' => 'cont_objeto',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'search_panel_field37' => array( 'field' => 'cont_objeto',
'type' => 'search_panel_field',
'required' => false ),
'grid_field10' => array( 'field' => 'cont_obligaciones',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'cont_obligaciones' ),
'search_panel_field38' => array( 'field' => 'cont_obligaciones',
'type' => 'search_panel_field',
'required' => false ),
'grid_field11' => array( 'field' => 'cont_plazo',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'cont_plazo' ),
'search_panel_field39' => array( 'field' => 'cont_plazo',
'type' => 'search_panel_field',
'required' => false ),
'grid_field12' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'ctb_tipo_nombre' ),
'search_panel_field40' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'search_panel_field',
'required' => false ),
'grid_field13' => array( 'field' => 'nombre_cargo',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'nombre_cargo' ),
'search_panel_field41' => array( 'field' => 'nombre_cargo',
'type' => 'search_panel_field',
'required' => false ),
'grid_field14' => array( 'field' => 'nombre_dependencia',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label14' => array( 'type' => 'grid_field_label',
'field' => 'nombre_dependencia' ),
'search_panel_field42' => array( 'field' => 'nombre_dependencia',
'type' => 'search_panel_field',
'required' => false ),
'grid_field15' => array( 'field' => 'id_depto_superior',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label15' => array( 'type' => 'grid_field_label',
'field' => 'id_depto_superior' ),
'search_panel_field43' => array( 'field' => 'id_depto_superior',
'type' => 'search_panel_field',
'required' => false ),
'grid_field16' => array( 'field' => 'Departamento_superior',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label16' => array( 'type' => 'grid_field_label',
'field' => 'Departamento_superior' ),
'search_panel_field44' => array( 'field' => 'Departamento_superior',
'type' => 'search_panel_field',
'required' => false ),
'grid_field17' => array( 'field' => 'cont_numpoliza',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label17' => array( 'type' => 'grid_field_label',
'field' => 'cont_numpoliza' ),
'search_panel_field45' => array( 'field' => 'cont_numpoliza',
'type' => 'search_panel_field',
'required' => false ),
'grid_field18' => array( 'field' => 'cont_secop_proceso',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label18' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_proceso' ),
'search_panel_field46' => array( 'field' => 'cont_secop_proceso',
'type' => 'search_panel_field',
'required' => false ),
'grid_field19' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label19' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_aprobgarantia' ),
'search_panel_field47' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'search_panel_field',
'required' => false ),
'grid_field20' => array( 'field' => 'cont_fechaapertura',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label20' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechaapertura' ),
'search_panel_field48' => array( 'field' => 'cont_fechaapertura',
'type' => 'search_panel_field',
'required' => false ),
'grid_field21' => array( 'field' => 'cont_munejec',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label21' => array( 'type' => 'grid_field_label',
'field' => 'cont_munejec' ),
'search_panel_field49' => array( 'field' => 'cont_munejec',
'type' => 'search_panel_field',
'required' => false ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_field22' => array( 'field' => 'cont_cesion',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label22' => array( 'type' => 'grid_field_label',
'field' => 'cont_cesion' ),
'search_panel_field50' => array( 'field' => 'cont_cesion',
'type' => 'search_panel_field',
'required' => false ),
'grid_field23' => array( 'field' => 'cont_modifica',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label23' => array( 'type' => 'grid_field_label',
'field' => 'cont_modifica' ),
'search_panel_field51' => array( 'field' => 'cont_modifica',
'type' => 'search_panel_field',
'required' => false ),
'grid_field24' => array( 'field' => 'Username',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label24' => array( 'type' => 'grid_field_label',
'field' => 'Username' ),
'search_panel_field52' => array( 'field' => 'Username',
'type' => 'search_panel_field',
'required' => false ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>