<?php
$dalTable_mindeporte_ct_06 = array();
$dalTable_mindeporte_ct_06["Id"] = array("type"=>200,"varname"=>"Id", "name" => "Id");
$dalTable_mindeporte_ct_06["FECHA DE RECIBIDO"] = array("type"=>200,"varname"=>"FECHA_DE_RECIBIDO", "name" => "FECHA DE RECIBIDO");
$dalTable_mindeporte_ct_06["DEPENDENCIA"] = array("type"=>200,"varname"=>"DEPENDENCIA", "name" => "DEPENDENCIA");
$dalTable_mindeporte_ct_06["OBSERVACIONES"] = array("type"=>200,"varname"=>"OBSERVACIONES", "name" => "OBSERVACIONES");
$dalTable_mindeporte_ct_06["REVISION DOCUMENTAL"] = array("type"=>200,"varname"=>"REVISION_DOCUMENTAL", "name" => "REVISION DOCUMENTAL");
$dalTable_mindeporte_ct_06["PROFESIONAL ELABORACION ABOGADOS"] = array("type"=>200,"varname"=>"PROFESIONAL_ELABORACION_ABOGADOS", "name" => "PROFESIONAL ELABORACION ABOGADOS");
$dalTable_mindeporte_ct_06["NUMERO DE CONTRATO"] = array("type"=>200,"varname"=>"NUMERO_DE_CONTRATO", "name" => "NUMERO DE CONTRATO");
$dalTable_mindeporte_ct_06["NUMERO DE PROCESO DE SECOP"] = array("type"=>200,"varname"=>"NUMERO_DE_PROCESO_DE_SECOP", "name" => "NUMERO DE PROCESO DE SECOP");
$dalTable_mindeporte_ct_06["VALIDACION PAA"] = array("type"=>200,"varname"=>"VALIDACION_PAA", "name" => "VALIDACION PAA");
$dalTable_mindeporte_ct_06["CODIGO UNSPSC"] = array("type"=>200,"varname"=>"CODIGO_UNSPSC", "name" => "CODIGO UNSPSC");
$dalTable_mindeporte_ct_06["cont_estado"] = array("type"=>200,"varname"=>"cont_estado", "name" => "cont_estado");
$dalTable_mindeporte_ct_06["CONTRATISTA"] = array("type"=>200,"varname"=>"CONTRATISTA", "name" => "CONTRATISTA");
$dalTable_mindeporte_ct_06["cont_nit_contra_ta"] = array("type"=>200,"varname"=>"cont_nit_contra_ta", "name" => "cont_nit_contra_ta");
$dalTable_mindeporte_ct_06["DV"] = array("type"=>200,"varname"=>"DV", "name" => "DV");
$dalTable_mindeporte_ct_06["PERSONA NATURAL - JURIDICA"] = array("type"=>200,"varname"=>"PERSONA_NATURAL___JURIDICA", "name" => "PERSONA NATURAL - JURIDICA");
$dalTable_mindeporte_ct_06["CORREO PERSONAL"] = array("type"=>200,"varname"=>"CORREO_PERSONAL", "name" => "CORREO PERSONAL");
$dalTable_mindeporte_ct_06["CORREO INSTITUCIONAL"] = array("type"=>200,"varname"=>"CORREO_INSTITUCIONAL", "name" => "CORREO INSTITUCIONAL");
$dalTable_mindeporte_ct_06["DIRECCION"] = array("type"=>200,"varname"=>"DIRECCION", "name" => "DIRECCION");
$dalTable_mindeporte_ct_06["TELEFONO"] = array("type"=>200,"varname"=>"TELEFONO", "name" => "TELEFONO");
$dalTable_mindeporte_ct_06["CELULAR"] = array("type"=>200,"varname"=>"CELULAR", "name" => "CELULAR");
$dalTable_mindeporte_ct_06["Ciudad residencia"] = array("type"=>200,"varname"=>"Ciudad_residencia", "name" => "Ciudad residencia");
$dalTable_mindeporte_ct_06["Banco"] = array("type"=>200,"varname"=>"Banco", "name" => "Banco");
$dalTable_mindeporte_ct_06["Tipo de cuenta"] = array("type"=>200,"varname"=>"Tipo_de_cuenta", "name" => "Tipo de cuenta");
$dalTable_mindeporte_ct_06["NUmero de cuenta"] = array("type"=>200,"varname"=>"NUmero_de_cuenta", "name" => "NUmero de cuenta");
$dalTable_mindeporte_ct_06["REgimen tributario"] = array("type"=>200,"varname"=>"REgimen_tributario", "name" => "REgimen tributario");
$dalTable_mindeporte_ct_06["Fecha de nacimiento"] = array("type"=>200,"varname"=>"Fecha_de_nacimiento", "name" => "Fecha de nacimiento");
$dalTable_mindeporte_ct_06["REGISTRO"] = array("type"=>200,"varname"=>"REGISTRO", "name" => "REGISTRO");
$dalTable_mindeporte_ct_06["DESIGNACION SUPERVISION"] = array("type"=>200,"varname"=>"DESIGNACION_SUPERVISION", "name" => "DESIGNACION SUPERVISION");
$dalTable_mindeporte_ct_06["OBJETO"] = array("type"=>200,"varname"=>"OBJETO", "name" => "OBJETO");
$dalTable_mindeporte_ct_06["TIPO DE CONTRATO"] = array("type"=>200,"varname"=>"TIPO_DE_CONTRATO", "name" => "TIPO DE CONTRATO");
$dalTable_mindeporte_ct_06["ESTADO"] = array("type"=>200,"varname"=>"ESTADO", "name" => "ESTADO");
$dalTable_mindeporte_ct_06["MODALIDAD DE SELECCION"] = array("type"=>200,"varname"=>"MODALIDAD_DE_SELECCION", "name" => "MODALIDAD DE SELECCION");
$dalTable_mindeporte_ct_06["FECHA SUSCRIPCION CONTRATO"] = array("type"=>200,"varname"=>"FECHA_SUSCRIPCION_CONTRATO", "name" => "FECHA SUSCRIPCION CONTRATO");
$dalTable_mindeporte_ct_06["FECHA DE INICIO"] = array("type"=>200,"varname"=>"FECHA_DE_INICIO", "name" => "FECHA DE INICIO");
$dalTable_mindeporte_ct_06["FECHA DE TERMINACION INICIAL"] = array("type"=>200,"varname"=>"FECHA_DE_TERMINACION_INICIAL", "name" => "FECHA DE TERMINACION INICIAL");
$dalTable_mindeporte_ct_06["FECHA DE TERMINACION DEFINITIVA"] = array("type"=>200,"varname"=>"FECHA_DE_TERMINACION_DEFINITIVA", "name" => "FECHA DE TERMINACION DEFINITIVA");
$dalTable_mindeporte_ct_06["PLAZO INICIAL DEL CONTRATO"] = array("type"=>200,"varname"=>"PLAZO_INICIAL_DEL_CONTRATO", "name" => "PLAZO INICIAL DEL CONTRATO");
$dalTable_mindeporte_ct_06["PLAZO EN DIAS"] = array("type"=>200,"varname"=>"PLAZO_EN_DIAS", "name" => "PLAZO EN DIAS");
$dalTable_mindeporte_ct_06["PLAZO DEL CONTRATO TOTAL"] = array("type"=>200,"varname"=>"PLAZO_DEL_CONTRATO_TOTAL", "name" => "PLAZO DEL CONTRATO TOTAL");
$dalTable_mindeporte_ct_06["PLAZO PARA LIQUIDAR SEGUN CTO"] = array("type"=>200,"varname"=>"PLAZO_PARA_LIQUIDAR_SEGUN_CTO", "name" => "PLAZO PARA LIQUIDAR SEGUN CTO");
$dalTable_mindeporte_ct_06["VALOR APORTE COLDEPORTES"] = array("type"=>200,"varname"=>"VALOR_APORTE_COLDEPORTES", "name" => "VALOR APORTE COLDEPORTES");
$dalTable_mindeporte_ct_06["ADICIONES EN VALOR COLDEPORTES"] = array("type"=>200,"varname"=>"ADICIONES_EN_VALOR_COLDEPORTES", "name" => "ADICIONES EN VALOR COLDEPORTES");
$dalTable_mindeporte_ct_06["VALOR APORTE CONTRATISTA"] = array("type"=>200,"varname"=>"VALOR_APORTE_CONTRATISTA", "name" => "VALOR APORTE CONTRATISTA");
$dalTable_mindeporte_ct_06["ADICIONES EN VALOR CONTRATISTA"] = array("type"=>200,"varname"=>"ADICIONES_EN_VALOR_CONTRATISTA", "name" => "ADICIONES EN VALOR CONTRATISTA");
$dalTable_mindeporte_ct_06["VALOR TOTAL APORTES COLDEPORTES"] = array("type"=>200,"varname"=>"VALOR_TOTAL_APORTES_COLDEPORTES", "name" => "VALOR TOTAL APORTES COLDEPORTES");
$dalTable_mindeporte_ct_06["VALOR TOTAL APORTES CONTRATISTA"] = array("type"=>200,"varname"=>"VALOR_TOTAL_APORTES_CONTRATISTA", "name" => "VALOR TOTAL APORTES CONTRATISTA");
$dalTable_mindeporte_ct_06["REDUCCIONES O DEVOLUCIONES EN VALOR"] = array("type"=>200,"varname"=>"REDUCCIONES_O_DEVOLUCIONES_EN_VALOR", "name" => "REDUCCIONES O DEVOLUCIONES EN VALOR");
$dalTable_mindeporte_ct_06["VALOR TOTAL DEL CONVENIO/CONTRATO"] = array("type"=>200,"varname"=>"VALOR_TOTAL_DEL_CONVENIO_CONTRATO", "name" => "VALOR TOTAL DEL CONVENIO/CONTRATO");
$dalTable_mindeporte_ct_06["VALOR TOTAL DEFINITIVO DEL CONVENIO/CONTRATO DESPUES DE ADICIONE"] = array("type"=>200,"varname"=>"VALOR_TOTAL_DEFINITIVO_DEL_CONVENIO_CONTRATO_DESPUES_DE_ADICIONE", "name" => "VALOR TOTAL DEFINITIVO DEL CONVENIO/CONTRATO DESPUES DE ADICIONE");
$dalTable_mindeporte_ct_06["VALOR HONORARIOS MENSUALES"] = array("type"=>200,"varname"=>"VALOR_HONORARIOS_MENSUALES", "name" => "VALOR HONORARIOS MENSUALES");
$dalTable_mindeporte_ct_06["GARANTIAS RIESGOS ASEGURADOS"] = array("type"=>200,"varname"=>"GARANTIAS_RIESGOS_ASEGURADOS", "name" => "GARANTIAS RIESGOS ASEGURADOS");
$dalTable_mindeporte_ct_06["CDP"] = array("type"=>200,"varname"=>"CDP", "name" => "CDP");
$dalTable_mindeporte_ct_06["FECHA"] = array("type"=>200,"varname"=>"FECHA", "name" => "FECHA");
$dalTable_mindeporte_ct_06["RUBRO"] = array("type"=>200,"varname"=>"RUBRO", "name" => "RUBRO");
$dalTable_mindeporte_ct_06["FUENTE DE RECURSOS"] = array("type"=>200,"varname"=>"FUENTE_DE_RECURSOS", "name" => "FUENTE DE RECURSOS");
$dalTable_mindeporte_ct_06["NoREGISTRO PRESUPUESTAL"] = array("type"=>200,"varname"=>"NoREGISTRO_PRESUPUESTAL", "name" => "NoREGISTRO PRESUPUESTAL");
$dalTable_mindeporte_ct_06["FECHA DEL REGISTRO PRESUPUESTAL"] = array("type"=>200,"varname"=>"FECHA_DEL_REGISTRO_PRESUPUESTAL", "name" => "FECHA DEL REGISTRO PRESUPUESTAL");
$dalTable_mindeporte_ct_06["VALOR REGISTRADO"] = array("type"=>200,"varname"=>"VALOR_REGISTRADO", "name" => "VALOR REGISTRADO");
$dalTable_mindeporte_ct_06["RUBRO ADICION"] = array("type"=>200,"varname"=>"RUBRO_ADICION", "name" => "RUBRO ADICION");
$dalTable_mindeporte_ct_06["RP ADICION 1"] = array("type"=>200,"varname"=>"RP_ADICION_1", "name" => "RP ADICION 1");
$dalTable_mindeporte_ct_06["VALOR REGISTRADO DE LA ADICION"] = array("type"=>200,"varname"=>"VALOR_REGISTRADO_DE_LA_ADICION", "name" => "VALOR REGISTRADO DE LA ADICION");
$dalTable_mindeporte_ct_06["Campo61"] = array("type"=>200,"varname"=>"Campo61", "name" => "Campo61");
$dalTable_mindeporte_ct_06["VALOR REGISTRADO TOTAL"] = array("type"=>200,"varname"=>"VALOR_REGISTRADO_TOTAL", "name" => "VALOR REGISTRADO TOTAL");
$dalTable_mindeporte_ct_06["ACTA INICIO"] = array("type"=>200,"varname"=>"ACTA_INICIO", "name" => "ACTA INICIO");
$dalTable_mindeporte_ct_06["POLIZA"] = array("type"=>200,"varname"=>"POLIZA", "name" => "POLIZA");
$dalTable_mindeporte_ct_06["FECHA EXPEDICION POLIZA"] = array("type"=>200,"varname"=>"FECHA_EXPEDICION_POLIZA", "name" => "FECHA EXPEDICION POLIZA");
$dalTable_mindeporte_ct_06["SUPERVISOR INICIAL"] = array("type"=>200,"varname"=>"SUPERVISOR_INICIAL", "name" => "SUPERVISOR INICIAL");
$dalTable_mindeporte_ct_06["CEDULA SUPERVISOR"] = array("type"=>200,"varname"=>"CEDULA_SUPERVISOR", "name" => "CEDULA SUPERVISOR");
$dalTable_mindeporte_ct_06["ORDENADOR DE GASTO"] = array("type"=>200,"varname"=>"ORDENADOR_DE_GASTO", "name" => "ORDENADOR DE GASTO");
$dalTable_mindeporte_ct_06["FECHA ULTIMA ACTUALIZACION"] = array("type"=>200,"varname"=>"FECHA_ULTIMA_ACTUALIZACION", "name" => "FECHA ULTIMA ACTUALIZACION");
$dalTable_mindeporte_ct_06["Campo70"] = array("type"=>200,"varname"=>"Campo70", "name" => "Campo70");

$dal_info["dbct_at_127_0_0_1___mindeporte_ct_06"] = &$dalTable_mindeporte_ct_06;
?>