<?php
$dalTableinfo_secop_import = array();
$dalTableinfo_secop_import["autonum"] = array("type"=>3,"varname"=>"autonum", "name" => "autonum");
$dalTableinfo_secop_import["id"] = array("type"=>200,"varname"=>"id", "name" => "id");
$dalTableinfo_secop_import["nombre_entidad"] = array("type"=>200,"varname"=>"nombre_entidad", "name" => "nombre_entidad");
$dalTableinfo_secop_import["nit_entidad"] = array("type"=>200,"varname"=>"nit_entidad", "name" => "nit_entidad");
$dalTableinfo_secop_import["departamento"] = array("type"=>200,"varname"=>"departamento", "name" => "departamento");
$dalTableinfo_secop_import["ciudad"] = array("type"=>200,"varname"=>"ciudad", "name" => "ciudad");
$dalTableinfo_secop_import["localizaci_n"] = array("type"=>200,"varname"=>"localizaci_n", "name" => "localizaci_n");
$dalTableinfo_secop_import["orden"] = array("type"=>200,"varname"=>"orden", "name" => "orden");
$dalTableinfo_secop_import["sector"] = array("type"=>200,"varname"=>"sector", "name" => "sector");
$dalTableinfo_secop_import["rama"] = array("type"=>200,"varname"=>"rama", "name" => "rama");
$dalTableinfo_secop_import["entidad_centralizada"] = array("type"=>200,"varname"=>"entidad_centralizada", "name" => "entidad_centralizada");
$dalTableinfo_secop_import["proceso_de_compra"] = array("type"=>200,"varname"=>"proceso_de_compra", "name" => "proceso_de_compra");
$dalTableinfo_secop_import["id_contrato"] = array("type"=>200,"varname"=>"id_contrato", "name" => "id_contrato");
$dalTableinfo_secop_import["referencia_del_contrato"] = array("type"=>200,"varname"=>"referencia_del_contrato", "name" => "referencia_del_contrato");
$dalTableinfo_secop_import["estado_contrato"] = array("type"=>200,"varname"=>"estado_contrato", "name" => "estado_contrato");
$dalTableinfo_secop_import["codigo_de_categoria_principal"] = array("type"=>200,"varname"=>"codigo_de_categoria_principal", "name" => "codigo_de_categoria_principal");
$dalTableinfo_secop_import["descripcion_del_proceso"] = array("type"=>200,"varname"=>"descripcion_del_proceso", "name" => "descripcion_del_proceso");
$dalTableinfo_secop_import["tipo_de_contrato"] = array("type"=>200,"varname"=>"tipo_de_contrato", "name" => "tipo_de_contrato");
$dalTableinfo_secop_import["modalidad_de_contratacion"] = array("type"=>200,"varname"=>"modalidad_de_contratacion", "name" => "modalidad_de_contratacion");
$dalTableinfo_secop_import["justificacion_modalidad_de"] = array("type"=>200,"varname"=>"justificacion_modalidad_de", "name" => "justificacion_modalidad_de");
$dalTableinfo_secop_import["fecha_de_firma"] = array("type"=>7,"varname"=>"fecha_de_firma", "name" => "fecha_de_firma");
$dalTableinfo_secop_import["fecha_de_inicio_del_contrato"] = array("type"=>7,"varname"=>"fecha_de_inicio_del_contrato", "name" => "fecha_de_inicio_del_contrato");
$dalTableinfo_secop_import["fecha_de_fin_del_contrato"] = array("type"=>7,"varname"=>"fecha_de_fin_del_contrato", "name" => "fecha_de_fin_del_contrato");
$dalTableinfo_secop_import["fecha_de_inicio_de_ejecucion"] = array("type"=>7,"varname"=>"fecha_de_inicio_de_ejecucion", "name" => "fecha_de_inicio_de_ejecucion");
$dalTableinfo_secop_import["fecha_de_fin_de_ejecucion"] = array("type"=>7,"varname"=>"fecha_de_fin_de_ejecucion", "name" => "fecha_de_fin_de_ejecucion");
$dalTableinfo_secop_import["condiciones_de_entrega"] = array("type"=>200,"varname"=>"condiciones_de_entrega", "name" => "condiciones_de_entrega");
$dalTableinfo_secop_import["tipodocproveedor"] = array("type"=>200,"varname"=>"tipodocproveedor", "name" => "tipodocproveedor");
$dalTableinfo_secop_import["documento_proveedor"] = array("type"=>200,"varname"=>"documento_proveedor", "name" => "documento_proveedor");
$dalTableinfo_secop_import["proveedor_adjudicado"] = array("type"=>200,"varname"=>"proveedor_adjudicado", "name" => "proveedor_adjudicado");
$dalTableinfo_secop_import["es_grupo"] = array("type"=>200,"varname"=>"es_grupo", "name" => "es_grupo");
$dalTableinfo_secop_import["es_pyme"] = array("type"=>200,"varname"=>"es_pyme", "name" => "es_pyme");
$dalTableinfo_secop_import["habilita_pago_adelantado"] = array("type"=>200,"varname"=>"habilita_pago_adelantado", "name" => "habilita_pago_adelantado");
$dalTableinfo_secop_import["liquidaci_n"] = array("type"=>200,"varname"=>"liquidaci_n", "name" => "liquidaci_n");
$dalTableinfo_secop_import["obligaci_n_ambiental"] = array("type"=>200,"varname"=>"obligaci_n_ambiental", "name" => "obligaci_n_ambiental");
$dalTableinfo_secop_import["obligaciones_postconsumo"] = array("type"=>200,"varname"=>"obligaciones_postconsumo", "name" => "obligaciones_postconsumo");
$dalTableinfo_secop_import["reversion"] = array("type"=>200,"varname"=>"reversion", "name" => "reversion");
$dalTableinfo_secop_import["valor_del_contrato"] = array("type"=>5,"varname"=>"valor_del_contrato", "name" => "valor_del_contrato");
$dalTableinfo_secop_import["valor_de_pago_adelantado"] = array("type"=>5,"varname"=>"valor_de_pago_adelantado", "name" => "valor_de_pago_adelantado");
$dalTableinfo_secop_import["valor_facturado"] = array("type"=>5,"varname"=>"valor_facturado", "name" => "valor_facturado");
$dalTableinfo_secop_import["valor_pendiente_de_pago"] = array("type"=>5,"varname"=>"valor_pendiente_de_pago", "name" => "valor_pendiente_de_pago");
$dalTableinfo_secop_import["valor_pagado"] = array("type"=>5,"varname"=>"valor_pagado", "name" => "valor_pagado");
$dalTableinfo_secop_import["valor_amortizado"] = array("type"=>5,"varname"=>"valor_amortizado", "name" => "valor_amortizado");
$dalTableinfo_secop_import["valor_pendiente_de"] = array("type"=>5,"varname"=>"valor_pendiente_de", "name" => "valor_pendiente_de");
$dalTableinfo_secop_import["valor_pendiente_de_ejecucion"] = array("type"=>5,"varname"=>"valor_pendiente_de_ejecucion", "name" => "valor_pendiente_de_ejecucion");
$dalTableinfo_secop_import["estado_bpin"] = array("type"=>200,"varname"=>"estado_bpin", "name" => "estado_bpin");
$dalTableinfo_secop_import["c_digo_bpin"] = array("type"=>200,"varname"=>"c_digo_bpin", "name" => "c_digo_bpin");
$dalTableinfo_secop_import["anno_bpin"] = array("type"=>200,"varname"=>"anno_bpin", "name" => "anno_bpin");
$dalTableinfo_secop_import["saldo_cdp"] = array("type"=>5,"varname"=>"saldo_cdp", "name" => "saldo_cdp");
$dalTableinfo_secop_import["saldo_vigencia"] = array("type"=>5,"varname"=>"saldo_vigencia", "name" => "saldo_vigencia");
$dalTableinfo_secop_import["espostconflicto"] = array("type"=>200,"varname"=>"espostconflicto", "name" => "espostconflicto");
$dalTableinfo_secop_import["urlproceso"] = array("type"=>200,"varname"=>"urlproceso", "name" => "urlproceso");
$dalTableinfo_secop_import["destino_gasto"] = array("type"=>200,"varname"=>"destino_gasto", "name" => "destino_gasto");
$dalTableinfo_secop_import["origen_de_los_recursos"] = array("type"=>200,"varname"=>"origen_de_los_recursos", "name" => "origen_de_los_recursos");
$dalTableinfo_secop_import["d_as_adicionados"] = array("type"=>5,"varname"=>"d_as_adicionados", "name" => "d_as_adicionados");
$dalTableinfo_secop_import["puntos_del_acuerdo"] = array("type"=>200,"varname"=>"puntos_del_acuerdo", "name" => "puntos_del_acuerdo");
$dalTableinfo_secop_import["pilares_del_acuerdo"] = array("type"=>200,"varname"=>"pilares_del_acuerdo", "name" => "pilares_del_acuerdo");
	$dalTableinfo_secop_import["autonum"]["key"]=true;
	$dalTableinfo_secop_import["id"]["key"]=true;

$dal_info["dbct_at_127_0_0_1__info_secop_import"] = &$dalTableinfo_secop_import;
?>