<?php
$dalTableq_bandejaentrada_supervisores = array();
$dalTableq_bandejaentrada_supervisores["id_cont"] = array("type"=>3,"varname"=>"id_cont", "name" => "id_cont");
$dalTableq_bandejaentrada_supervisores["cont_nit_contra_ta"] = array("type"=>200,"varname"=>"cont_nit_contra_ta", "name" => "cont_nit_contra_ta");
$dalTableq_bandejaentrada_supervisores["cont_estado"] = array("type"=>3,"varname"=>"cont_estado", "name" => "cont_estado");
$dalTableq_bandejaentrada_supervisores["numcontrato"] = array("type"=>200,"varname"=>"numcontrato", "name" => "numcontrato");
$dalTableq_bandejaentrada_supervisores["pre_contnumero"] = array("type"=>200,"varname"=>"pre_contnumero", "name" => "pre_contnumero");
$dalTableq_bandejaentrada_supervisores["contnumero"] = array("type"=>200,"varname"=>"contnumero", "name" => "contnumero");
$dalTableq_bandejaentrada_supervisores["cont_ano"] = array("type"=>2,"varname"=>"cont_ano", "name" => "cont_ano");
$dalTableq_bandejaentrada_supervisores["cont_codrubro"] = array("type"=>200,"varname"=>"cont_codrubro", "name" => "cont_codrubro");
$dalTableq_bandejaentrada_supervisores["cont_catalogo_presupuestal"] = array("type"=>200,"varname"=>"cont_catalogo_presupuestal", "name" => "cont_catalogo_presupuestal");
$dalTableq_bandejaentrada_supervisores["cont_fecha_inicio"] = array("type"=>7,"varname"=>"cont_fecha_inicio", "name" => "cont_fecha_inicio");
$dalTableq_bandejaentrada_supervisores["cont_fechafinal"] = array("type"=>7,"varname"=>"cont_fechafinal", "name" => "cont_fechafinal");
$dalTableq_bandejaentrada_supervisores["PLAZO"] = array("type"=>3,"varname"=>"PLAZO", "name" => "PLAZO");
$dalTableq_bandejaentrada_supervisores["cont_periodicidad"] = array("type"=>3,"varname"=>"cont_periodicidad", "name" => "cont_periodicidad");
$dalTableq_bandejaentrada_supervisores["cont_valorinicial"] = array("type"=>5,"varname"=>"cont_valorinicial", "name" => "cont_valorinicial");
$dalTableq_bandejaentrada_supervisores["cont_valormensual"] = array("type"=>5,"varname"=>"cont_valormensual", "name" => "cont_valormensual");
$dalTableq_bandejaentrada_supervisores["cont_secop_enlace"] = array("type"=>200,"varname"=>"cont_secop_enlace", "name" => "cont_secop_enlace");
$dalTableq_bandejaentrada_supervisores["documento_id"] = array("type"=>3,"varname"=>"documento_id", "name" => "documento_id");
$dalTableq_bandejaentrada_supervisores["nombres"] = array("type"=>200,"varname"=>"nombres", "name" => "nombres");
$dalTableq_bandejaentrada_supervisores["apellidos"] = array("type"=>200,"varname"=>"apellidos", "name" => "apellidos");
$dalTableq_bandejaentrada_supervisores["nombresupfull"] = array("type"=>200,"varname"=>"nombresupfull", "name" => "nombresupfull");
$dalTableq_bandejaentrada_supervisores["cargo_id"] = array("type"=>3,"varname"=>"cargo_id", "name" => "cargo_id");
$dalTableq_bandejaentrada_supervisores["dependencia_id"] = array("type"=>3,"varname"=>"dependencia_id", "name" => "dependencia_id");
$dalTableq_bandejaentrada_supervisores["sup_fechanot"] = array("type"=>135,"varname"=>"sup_fechanot", "name" => "sup_fechanot");
$dalTableq_bandejaentrada_supervisores["sup_mailnot"] = array("type"=>200,"varname"=>"sup_mailnot", "name" => "sup_mailnot");
$dalTableq_bandejaentrada_supervisores["sup_status"] = array("type"=>16,"varname"=>"sup_status", "name" => "sup_status");
$dalTableq_bandejaentrada_supervisores["idusrglobal_fk"] = array("type"=>3,"varname"=>"idusrglobal_fk", "name" => "idusrglobal_fk");
$dalTableq_bandejaentrada_supervisores["contractor_name"] = array("type"=>200,"varname"=>"contractor_name", "name" => "contractor_name");
$dalTableq_bandejaentrada_supervisores["contractor_lname"] = array("type"=>200,"varname"=>"contractor_lname", "name" => "contractor_lname");
$dalTableq_bandejaentrada_supervisores["contractor_nombresfull"] = array("type"=>200,"varname"=>"contractor_nombresfull", "name" => "contractor_nombresfull");
$dalTableq_bandejaentrada_supervisores["contractor_email"] = array("type"=>200,"varname"=>"contractor_email", "name" => "contractor_email");
$dalTableq_bandejaentrada_supervisores["contractor_email_mincit"] = array("type"=>200,"varname"=>"contractor_email_mincit", "name" => "contractor_email_mincit");
$dalTableq_bandejaentrada_supervisores["prenumero"] = array("type"=>200,"varname"=>"prenumero", "name" => "prenumero");
$dalTableq_bandejaentrada_supervisores["numregistro"] = array("type"=>200,"varname"=>"numregistro", "name" => "numregistro");
$dalTableq_bandejaentrada_supervisores["cont_unspsc"] = array("type"=>200,"varname"=>"cont_unspsc", "name" => "cont_unspsc");
$dalTableq_bandejaentrada_supervisores["cont_tipo_rubro"] = array("type"=>200,"varname"=>"cont_tipo_rubro", "name" => "cont_tipo_rubro");
$dalTableq_bandejaentrada_supervisores["cont_tipopre"] = array("type"=>200,"varname"=>"cont_tipopre", "name" => "cont_tipopre");
$dalTableq_bandejaentrada_supervisores["cont_causalc"] = array("type"=>3,"varname"=>"cont_causalc", "name" => "cont_causalc");
$dalTableq_bandejaentrada_supervisores["cont_objeto"] = array("type"=>201,"varname"=>"cont_objeto", "name" => "cont_objeto");
$dalTableq_bandejaentrada_supervisores["cont_obligaciones"] = array("type"=>201,"varname"=>"cont_obligaciones", "name" => "cont_obligaciones");
$dalTableq_bandejaentrada_supervisores["cont_plazo"] = array("type"=>201,"varname"=>"cont_plazo", "name" => "cont_plazo");
$dalTableq_bandejaentrada_supervisores["ctb_tipo_nombre"] = array("type"=>200,"varname"=>"ctb_tipo_nombre", "name" => "ctb_tipo_nombre");
$dalTableq_bandejaentrada_supervisores["nombre_cargo"] = array("type"=>200,"varname"=>"nombre_cargo", "name" => "nombre_cargo");
$dalTableq_bandejaentrada_supervisores["nombre_dependencia"] = array("type"=>200,"varname"=>"nombre_dependencia", "name" => "nombre_dependencia");
$dalTableq_bandejaentrada_supervisores["id_depto_superior"] = array("type"=>3,"varname"=>"id_depto_superior", "name" => "id_depto_superior");
$dalTableq_bandejaentrada_supervisores["Departamento_superior"] = array("type"=>200,"varname"=>"Departamento_superior", "name" => "Departamento_superior");
$dalTableq_bandejaentrada_supervisores["cont_numpoliza"] = array("type"=>200,"varname"=>"cont_numpoliza", "name" => "cont_numpoliza");
$dalTableq_bandejaentrada_supervisores["cont_secop_proceso"] = array("type"=>200,"varname"=>"cont_secop_proceso", "name" => "cont_secop_proceso");
$dalTableq_bandejaentrada_supervisores["cont_fecha_aprobgarantia"] = array("type"=>7,"varname"=>"cont_fecha_aprobgarantia", "name" => "cont_fecha_aprobgarantia");
$dalTableq_bandejaentrada_supervisores["cont_fechaapertura"] = array("type"=>7,"varname"=>"cont_fechaapertura", "name" => "cont_fechaapertura");
$dalTableq_bandejaentrada_supervisores["cont_munejec"] = array("type"=>200,"varname"=>"cont_munejec", "name" => "cont_munejec");
$dalTableq_bandejaentrada_supervisores["cont_cesion"] = array("type"=>16,"varname"=>"cont_cesion", "name" => "cont_cesion");
$dalTableq_bandejaentrada_supervisores["cont_modifica"] = array("type"=>16,"varname"=>"cont_modifica", "name" => "cont_modifica");

$dal_info["dbct_at_127_0_0_1__q_bandejaentrada_supervisores"] = &$dalTableq_bandejaentrada_supervisores;
?>