<?php
$dalTableq_global_supervisores = array();
$dalTableq_global_supervisores["interventor_id"] = array("type"=>3,"varname"=>"interventor_id", "name" => "interventor_id");
$dalTableq_global_supervisores["id_cont_fk"] = array("type"=>3,"varname"=>"id_cont_fk", "name" => "id_cont_fk");
$dalTableq_global_supervisores["cont_hash_fk"] = array("type"=>200,"varname"=>"cont_hash_fk", "name" => "cont_hash_fk");
$dalTableq_global_supervisores["idusrglobal_fk"] = array("type"=>3,"varname"=>"idusrglobal_fk", "name" => "idusrglobal_fk");
$dalTableq_global_supervisores["sys_date"] = array("type"=>7,"varname"=>"sys_date", "name" => "sys_date");
$dalTableq_global_supervisores["sys_time"] = array("type"=>135,"varname"=>"sys_time", "name" => "sys_time");
$dalTableq_global_supervisores["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user");
$dalTableq_global_supervisores["usr_name"] = array("type"=>200,"varname"=>"usr_name", "name" => "usr_name");
$dalTableq_global_supervisores["usr_lname"] = array("type"=>200,"varname"=>"usr_lname", "name" => "usr_lname");
$dalTableq_global_supervisores["usr_email"] = array("type"=>200,"varname"=>"usr_email", "name" => "usr_email");
$dalTableq_global_supervisores["usr_dependencia"] = array("type"=>200,"varname"=>"usr_dependencia", "name" => "usr_dependencia");
$dalTableq_global_supervisores["usr_personalid"] = array("type"=>3,"varname"=>"usr_personalid", "name" => "usr_personalid");
$dalTableq_global_supervisores["Username"] = array("type"=>200,"varname"=>"Username", "name" => "Username");
$dalTableq_global_supervisores["sup_status"] = array("type"=>16,"varname"=>"sup_status", "name" => "sup_status");
$dalTableq_global_supervisores["sup_fechanot"] = array("type"=>135,"varname"=>"sup_fechanot", "name" => "sup_fechanot");
$dalTableq_global_supervisores["sup_horanot"] = array("type"=>134,"varname"=>"sup_horanot", "name" => "sup_horanot");
$dalTableq_global_supervisores["pre_contnumero"] = array("type"=>200,"varname"=>"pre_contnumero", "name" => "pre_contnumero");
$dalTableq_global_supervisores["contnumero"] = array("type"=>200,"varname"=>"contnumero", "name" => "contnumero");
$dalTableq_global_supervisores["NCONTRATO"] = array("type"=>200,"varname"=>"NCONTRATO", "name" => "NCONTRATO");
$dalTableq_global_supervisores["cont_ano"] = array("type"=>2,"varname"=>"cont_ano", "name" => "cont_ano");
$dalTableq_global_supervisores["cont_fecha_inicio"] = array("type"=>7,"varname"=>"cont_fecha_inicio", "name" => "cont_fecha_inicio");
$dalTableq_global_supervisores["cont_fechafinal"] = array("type"=>7,"varname"=>"cont_fechafinal", "name" => "cont_fechafinal");
$dalTableq_global_supervisores["cont_estado"] = array("type"=>3,"varname"=>"cont_estado", "name" => "cont_estado");
$dalTableq_global_supervisores["cont_nit_contra_ta"] = array("type"=>200,"varname"=>"cont_nit_contra_ta", "name" => "cont_nit_contra_ta");
$dalTableq_global_supervisores["contractor_name"] = array("type"=>200,"varname"=>"contractor_name", "name" => "contractor_name");
$dalTableq_global_supervisores["cont_informessug"] = array("type"=>3,"varname"=>"cont_informessug", "name" => "cont_informessug");
$dalTableq_global_supervisores["cont_periodicidad"] = array("type"=>3,"varname"=>"cont_periodicidad", "name" => "cont_periodicidad");
$dalTableq_global_supervisores["periodo_name"] = array("type"=>200,"varname"=>"periodo_name", "name" => "periodo_name");
$dalTableq_global_supervisores["periodo_value"] = array("type"=>3,"varname"=>"periodo_value", "name" => "periodo_value");
$dalTableq_global_supervisores["periodo_dias"] = array("type"=>3,"varname"=>"periodo_dias", "name" => "periodo_dias");
$dalTableq_global_supervisores["usr_dep"] = array("type"=>3,"varname"=>"usr_dep", "name" => "usr_dep");
$dalTableq_global_supervisores["usr_cargo"] = array("type"=>3,"varname"=>"usr_cargo", "name" => "usr_cargo");
$dalTableq_global_supervisores["contractor_type"] = array("type"=>200,"varname"=>"contractor_type", "name" => "contractor_type");
$dalTableq_global_supervisores["dpd_dsdpn_b"] = array("type"=>200,"varname"=>"dpd_dsdpn_b", "name" => "dpd_dsdpn_b");
$dalTableq_global_supervisores["nomcar"] = array("type"=>200,"varname"=>"nomcar", "name" => "nomcar");

$dal_info["dbct_at_127_0_0_1__q_global_supervisores"] = &$dalTableq_global_supervisores;
?>