<?php
$dalTablecontractor_master = array();
$dalTablecontractor_master["contractor_id"] = array("type"=>3,"varname"=>"contractor_id", "name" => "contractor_id");
$dalTablecontractor_master["contractor_type"] = array("type"=>200,"varname"=>"contractor_type", "name" => "contractor_type");
$dalTablecontractor_master["contractor_doc_id"] = array("type"=>200,"varname"=>"contractor_doc_id", "name" => "contractor_doc_id");
$dalTablecontractor_master["contractor_doc_dv"] = array("type"=>200,"varname"=>"contractor_doc_dv", "name" => "contractor_doc_dv");
$dalTablecontractor_master["contractor_pwd"] = array("type"=>200,"varname"=>"contractor_pwd", "name" => "contractor_pwd");
$dalTablecontractor_master["contractor_image"] = array("type"=>200,"varname"=>"contractor_image", "name" => "contractor_image");
$dalTablecontractor_master["contractor_name"] = array("type"=>200,"varname"=>"contractor_name", "name" => "contractor_name");
$dalTablecontractor_master["contractor_lname"] = array("type"=>200,"varname"=>"contractor_lname", "name" => "contractor_lname");
$dalTablecontractor_master["contractor_nombresfull"] = array("type"=>200,"varname"=>"contractor_nombresfull", "name" => "contractor_nombresfull");
$dalTablecontractor_master["enlace_sigep"] = array("type"=>200,"varname"=>"enlace_sigep", "name" => "enlace_sigep");
$dalTablecontractor_master["contractor_email"] = array("type"=>200,"varname"=>"contractor_email", "name" => "contractor_email");
$dalTablecontractor_master["contractor_email_mincit"] = array("type"=>200,"varname"=>"contractor_email_mincit", "name" => "contractor_email_mincit");
$dalTablecontractor_master["contractor_address"] = array("type"=>200,"varname"=>"contractor_address", "name" => "contractor_address");
$dalTablecontractor_master["contractor_phone"] = array("type"=>200,"varname"=>"contractor_phone", "name" => "contractor_phone");
$dalTablecontractor_master["contractor_mobile"] = array("type"=>200,"varname"=>"contractor_mobile", "name" => "contractor_mobile");
$dalTablecontractor_master["contractor_city"] = array("type"=>200,"varname"=>"contractor_city", "name" => "contractor_city");
$dalTablecontractor_master["contractor_sup_jerarquico"] = array("type"=>3,"varname"=>"contractor_sup_jerarquico", "name" => "contractor_sup_jerarquico");
$dalTablecontractor_master["contractor_dependencia"] = array("type"=>3,"varname"=>"contractor_dependencia", "name" => "contractor_dependencia");
$dalTablecontractor_master["bank_name"] = array("type"=>3,"varname"=>"bank_name", "name" => "bank_name");
$dalTablecontractor_master["bank_cta_type"] = array("type"=>3,"varname"=>"bank_cta_type", "name" => "bank_cta_type");
$dalTablecontractor_master["bank_cta_number"] = array("type"=>200,"varname"=>"bank_cta_number", "name" => "bank_cta_number");
$dalTablecontractor_master["iva_regimen"] = array("type"=>16,"varname"=>"iva_regimen", "name" => "iva_regimen");
$dalTablecontractor_master["sys_update"] = array("type"=>16,"varname"=>"sys_update", "name" => "sys_update");
$dalTablecontractor_master["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user");
$dalTablecontractor_master["sys_date"] = array("type"=>7,"varname"=>"sys_date", "name" => "sys_date");
$dalTablecontractor_master["sys_level"] = array("type"=>16,"varname"=>"sys_level", "name" => "sys_level");
$dalTablecontractor_master["sys_status"] = array("type"=>16,"varname"=>"sys_status", "name" => "sys_status");
$dalTablecontractor_master["sys_last_upd"] = array("type"=>135,"varname"=>"sys_last_upd", "name" => "sys_last_upd");
$dalTablecontractor_master["groupid"] = array("type"=>200,"varname"=>"groupid", "name" => "groupid");
$dalTablecontractor_master["active"] = array("type"=>3,"varname"=>"active", "name" => "active");
$dalTablecontractor_master["contractor_dependientes"] = array("type"=>16,"varname"=>"contractor_dependientes", "name" => "contractor_dependientes");
$dalTablecontractor_master["contractor_medicinapre_file"] = array("type"=>200,"varname"=>"contractor_medicinapre_file", "name" => "contractor_medicinapre_file");
$dalTablecontractor_master["contractor_picmonetaria_file"] = array("type"=>200,"varname"=>"contractor_picmonetaria_file", "name" => "contractor_picmonetaria_file");
$dalTablecontractor_master["contractor_decljur"] = array("type"=>200,"varname"=>"contractor_decljur", "name" => "contractor_decljur");
$dalTablecontractor_master["contractor_eps"] = array("type"=>3,"varname"=>"contractor_eps", "name" => "contractor_eps");
$dalTablecontractor_master["contractor_fondopensiones"] = array("type"=>3,"varname"=>"contractor_fondopensiones", "name" => "contractor_fondopensiones");
$dalTablecontractor_master["contractor_cajacompensacion"] = array("type"=>3,"varname"=>"contractor_cajacompensacion", "name" => "contractor_cajacompensacion");
$dalTablecontractor_master["contractor_arl"] = array("type"=>3,"varname"=>"contractor_arl", "name" => "contractor_arl");
$dalTablecontractor_master["ubica_dep"] = array("type"=>3,"varname"=>"ubica_dep", "name" => "ubica_dep");
$dalTablecontractor_master["ubica_extension"] = array("type"=>200,"varname"=>"ubica_extension", "name" => "ubica_extension");
$dalTablecontractor_master["dem_genero"] = array("type"=>200,"varname"=>"dem_genero", "name" => "dem_genero");
$dalTablecontractor_master["dem_ocupacion"] = array("type"=>3,"varname"=>"dem_ocupacion", "name" => "dem_ocupacion");
$dalTablecontractor_master["dem_profesion"] = array("type"=>200,"varname"=>"dem_profesion", "name" => "dem_profesion");
$dalTablecontractor_master["ct_fecha_nacimiento"] = array("type"=>7,"varname"=>"ct_fecha_nacimiento", "name" => "ct_fecha_nacimiento");
$dalTablecontractor_master["ct_nacionalidad"] = array("type"=>200,"varname"=>"ct_nacionalidad", "name" => "ct_nacionalidad");
$dalTablecontractor_master["dem_edad"] = array("type"=>3,"varname"=>"dem_edad", "name" => "dem_edad");
$dalTablecontractor_master["dem_educacion"] = array("type"=>3,"varname"=>"dem_educacion", "name" => "dem_educacion");
$dalTablecontractor_master["dem_discapacidad"] = array("type"=>200,"varname"=>"dem_discapacidad", "name" => "dem_discapacidad");
$dalTablecontractor_master["emergencia"] = array("type"=>200,"varname"=>"emergencia", "name" => "emergencia");
$dalTablecontractor_master["terms_msj"] = array("type"=>201,"varname"=>"terms_msj", "name" => "terms_msj");
$dalTablecontractor_master["terms_acepta"] = array("type"=>16,"varname"=>"terms_acepta", "name" => "terms_acepta");
$dalTablecontractor_master["signature"] = array("type"=>200,"varname"=>"signature", "name" => "signature");
$dalTablecontractor_master["pin"] = array("type"=>200,"varname"=>"pin", "name" => "pin");
	$dalTablecontractor_master["contractor_id"]["key"]=true;
	$dalTablecontractor_master["contractor_doc_id"]["key"]=true;

$dal_info["dbct_at_127_0_0_1__contractor_master"] = &$dalTablecontractor_master;
?>