<?php
$dalTableinforme_intersup = array();
$dalTableinforme_intersup["inf_id"] = array("type"=>3,"varname"=>"inf_id", "name" => "inf_id");
$dalTableinforme_intersup["id_cont_fk"] = array("type"=>3,"varname"=>"id_cont_fk", "name" => "id_cont_fk");
$dalTableinforme_intersup["inf_consecutivo"] = array("type"=>3,"varname"=>"inf_consecutivo", "name" => "inf_consecutivo");
$dalTableinforme_intersup["inf_hash"] = array("type"=>200,"varname"=>"inf_hash", "name" => "inf_hash");
$dalTableinforme_intersup["inf_estado"] = array("type"=>16,"varname"=>"inf_estado", "name" => "inf_estado");
$dalTableinforme_intersup["inf_fechapresenta"] = array("type"=>7,"varname"=>"inf_fechapresenta", "name" => "inf_fechapresenta");
$dalTableinforme_intersup["inf_periodicidad"] = array("type"=>16,"varname"=>"inf_periodicidad", "name" => "inf_periodicidad");
$dalTableinforme_intersup["inf_fecharep_i"] = array("type"=>7,"varname"=>"inf_fecharep_i", "name" => "inf_fecharep_i");
$dalTableinforme_intersup["inf_fecharep_f"] = array("type"=>7,"varname"=>"inf_fecharep_f", "name" => "inf_fecharep_f");
$dalTableinforme_intersup["inf_numerocontrato"] = array("type"=>200,"varname"=>"inf_numerocontrato", "name" => "inf_numerocontrato");
$dalTableinforme_intersup["inf_anio"] = array("type"=>2,"varname"=>"inf_anio", "name" => "inf_anio");
$dalTableinforme_intersup["inf_prenum"] = array("type"=>200,"varname"=>"inf_prenum", "name" => "inf_prenum");
$dalTableinforme_intersup["inf_doccontratista"] = array("type"=>200,"varname"=>"inf_doccontratista", "name" => "inf_doccontratista");
$dalTableinforme_intersup["inf_nombrecontratista"] = array("type"=>200,"varname"=>"inf_nombrecontratista", "name" => "inf_nombrecontratista");
$dalTableinforme_intersup["inf_valorcontrato"] = array("type"=>5,"varname"=>"inf_valorcontrato", "name" => "inf_valorcontrato");
$dalTableinforme_intersup["inf_adicionreduc"] = array("type"=>200,"varname"=>"inf_adicionreduc", "name" => "inf_adicionreduc");
$dalTableinforme_intersup["inf_cdp"] = array("type"=>200,"varname"=>"inf_cdp", "name" => "inf_cdp");
$dalTableinforme_intersup["inf_rp"] = array("type"=>200,"varname"=>"inf_rp", "name" => "inf_rp");
$dalTableinforme_intersup["inf_rubrocode"] = array("type"=>200,"varname"=>"inf_rubrocode", "name" => "inf_rubrocode");
$dalTableinforme_intersup["inf_rubroname"] = array("type"=>200,"varname"=>"inf_rubroname", "name" => "inf_rubroname");
$dalTableinforme_intersup["inf_objeto"] = array("type"=>200,"varname"=>"inf_objeto", "name" => "inf_objeto");
$dalTableinforme_intersup["inf_fechasuscripcion"] = array("type"=>7,"varname"=>"inf_fechasuscripcion", "name" => "inf_fechasuscripcion");
$dalTableinforme_intersup["inf_fechacont_i"] = array("type"=>7,"varname"=>"inf_fechacont_i", "name" => "inf_fechacont_i");
$dalTableinforme_intersup["inf_fechacont_f"] = array("type"=>7,"varname"=>"inf_fechacont_f", "name" => "inf_fechacont_f");
$dalTableinforme_intersup["inf_plazo"] = array("type"=>200,"varname"=>"inf_plazo", "name" => "inf_plazo");
$dalTableinforme_intersup["inf_vigencia"] = array("type"=>200,"varname"=>"inf_vigencia", "name" => "inf_vigencia");
$dalTableinforme_intersup["inf_modificacionesplazo"] = array("type"=>200,"varname"=>"inf_modificacionesplazo", "name" => "inf_modificacionesplazo");
$dalTableinforme_intersup["inf_intersup"] = array("type"=>200,"varname"=>"inf_intersup", "name" => "inf_intersup");
$dalTableinforme_intersup["inf_nombre"] = array("type"=>200,"varname"=>"inf_nombre", "name" => "inf_nombre");
$dalTableinforme_intersup["inf_cargo"] = array("type"=>200,"varname"=>"inf_cargo", "name" => "inf_cargo");
$dalTableinforme_intersup["inf_dependencia"] = array("type"=>200,"varname"=>"inf_dependencia", "name" => "inf_dependencia");
$dalTableinforme_intersup["inf_avgejecucion"] = array("type"=>5,"varname"=>"inf_avgejecucion", "name" => "inf_avgejecucion");
$dalTableinforme_intersup["inf_actividades"] = array("type"=>200,"varname"=>"inf_actividades", "name" => "inf_actividades");
$dalTableinforme_intersup["inf_declarainconf"] = array("type"=>200,"varname"=>"inf_declarainconf", "name" => "inf_declarainconf");
$dalTableinforme_intersup["inf_declarainconf_obs"] = array("type"=>200,"varname"=>"inf_declarainconf_obs", "name" => "inf_declarainconf_obs");
$dalTableinforme_intersup["inf_incumplimiento"] = array("type"=>200,"varname"=>"inf_incumplimiento", "name" => "inf_incumplimiento");
$dalTableinforme_intersup["inf_incumplimiento_obs"] = array("type"=>200,"varname"=>"inf_incumplimiento_obs", "name" => "inf_incumplimiento_obs");
$dalTableinforme_intersup["inf_otrosaspectostecnicos"] = array("type"=>200,"varname"=>"inf_otrosaspectostecnicos", "name" => "inf_otrosaspectostecnicos");
$dalTableinforme_intersup["inf_recomyobserva"] = array("type"=>200,"varname"=>"inf_recomyobserva", "name" => "inf_recomyobserva");
$dalTableinforme_intersup["sign_date"] = array("type"=>7,"varname"=>"sign_date", "name" => "sign_date");
$dalTableinforme_intersup["sign_hash"] = array("type"=>200,"varname"=>"sign_hash", "name" => "sign_hash");
$dalTableinforme_intersup["sign_file"] = array("type"=>200,"varname"=>"sign_file", "name" => "sign_file");
$dalTableinforme_intersup["sign_mailnot"] = array("type"=>200,"varname"=>"sign_mailnot", "name" => "sign_mailnot");
$dalTableinforme_intersup["file_verifica"] = array("type"=>200,"varname"=>"file_verifica", "name" => "file_verifica");
$dalTableinforme_intersup["sign_verificacert"] = array("type"=>16,"varname"=>"sign_verificacert", "name" => "sign_verificacert");
$dalTableinforme_intersup["cert_date"] = array("type"=>7,"varname"=>"cert_date", "name" => "cert_date");
$dalTableinforme_intersup["cert_file"] = array("type"=>200,"varname"=>"cert_file", "name" => "cert_file");
$dalTableinforme_intersup["cert_mail"] = array("type"=>200,"varname"=>"cert_mail", "name" => "cert_mail");
$dalTableinforme_intersup["cert_compare"] = array("type"=>200,"varname"=>"cert_compare", "name" => "cert_compare");
$dalTableinforme_intersup["inf_ultimopago"] = array("type"=>16,"varname"=>"inf_ultimopago", "name" => "inf_ultimopago");
$dalTableinforme_intersup["sys_date"] = array("type"=>135,"varname"=>"sys_date", "name" => "sys_date");
$dalTableinforme_intersup["inf_mail_a"] = array("type"=>200,"varname"=>"inf_mail_a", "name" => "inf_mail_a");
$dalTableinforme_intersup["inf_mail_b"] = array("type"=>200,"varname"=>"inf_mail_b", "name" => "inf_mail_b");
$dalTableinforme_intersup["url_secop"] = array("type"=>200,"varname"=>"url_secop", "name" => "url_secop");
$dalTableinforme_intersup["num_poliza"] = array("type"=>200,"varname"=>"num_poliza", "name" => "num_poliza");
$dalTableinforme_intersup["mun_ejec"] = array("type"=>200,"varname"=>"mun_ejec", "name" => "mun_ejec");
$dalTableinforme_intersup["cont_cesion"] = array("type"=>16,"varname"=>"cont_cesion", "name" => "cont_cesion");
$dalTableinforme_intersup["cont_modifica"] = array("type"=>16,"varname"=>"cont_modifica", "name" => "cont_modifica");
	$dalTableinforme_intersup["inf_id"]["key"]=true;

$dal_info["dbct_at_127_0_0_1__informe_intersup"] = &$dalTableinforme_intersup;
?>