<?php
$dalTablenptre = array();
$dalTablenptre["npt_nrced_b"] = array("type"=>14,"varname"=>"npt_nrced_b", "name" => "npt_nrced_b");
$dalTablenptre["npt_nrnov_b"] = array("type"=>14,"varname"=>"npt_nrnov_b", "name" => "npt_nrnov_b");
$dalTablenptre["npt_tpnpt_b"] = array("type"=>200,"varname"=>"npt_tpnpt_b", "name" => "npt_tpnpt_b");
$dalTablenptre["npt_cdmotnpt_b"] = array("type"=>200,"varname"=>"npt_cdmotnpt_b", "name" => "npt_cdmotnpt_b");
$dalTablenptre["npt_fcini_b"] = array("type"=>7,"varname"=>"npt_fcini_b", "name" => "npt_fcini_b");
$dalTablenptre["npt_cdregdpn_b"] = array("type"=>200,"varname"=>"npt_cdregdpn_b", "name" => "npt_cdregdpn_b");
$dalTablenptre["npt_rocoddpn_b"] = array("type"=>200,"varname"=>"npt_rocoddpn_b", "name" => "npt_rocoddpn_b");
$dalTablenptre["npt_dsdpnabr_b"] = array("type"=>200,"varname"=>"npt_dsdpnabr_b", "name" => "npt_dsdpnabr_b");
$dalTablenptre["npt_cargo_b"] = array("type"=>200,"varname"=>"npt_cargo_b", "name" => "npt_cargo_b");
$dalTablenptre["npt_coplz_b"] = array("type"=>3,"varname"=>"npt_coplz_b", "name" => "npt_coplz_b");
$dalTablenptre["npt_obser_b"] = array("type"=>200,"varname"=>"npt_obser_b", "name" => "npt_obser_b");
$dalTablenptre["npt_nmcarcat_b"] = array("type"=>200,"varname"=>"npt_nmcarcat_b", "name" => "npt_nmcarcat_b");
$dalTablenptre["npt_nmcarnom_b"] = array("type"=>200,"varname"=>"npt_nmcarnom_b", "name" => "npt_nmcarnom_b");
$dalTablenptre["npt_piapenom_b"] = array("type"=>200,"varname"=>"npt_piapenom_b", "name" => "npt_piapenom_b");
$dalTablenptre["npt_seapenom_b"] = array("type"=>200,"varname"=>"npt_seapenom_b", "name" => "npt_seapenom_b");
$dalTablenptre["npt_nmnom_b"] = array("type"=>200,"varname"=>"npt_nmnom_b", "name" => "npt_nmnom_b");
$dalTablenptre["npt_ancon_b"] = array("type"=>3,"varname"=>"npt_ancon_b", "name" => "npt_ancon_b");
$dalTablenptre["npt_nrcon_b"] = array("type"=>3,"varname"=>"npt_nrcon_b", "name" => "npt_nrcon_b");
$dalTablenptre["npt_fcfin_b"] = array("type"=>7,"varname"=>"npt_fcfin_b", "name" => "npt_fcfin_b");
$dalTablenptre["npt_fcinirea_b"] = array("type"=>7,"varname"=>"npt_fcinirea_b", "name" => "npt_fcinirea_b");
$dalTablenptre["npt_fcfinrea_b"] = array("type"=>7,"varname"=>"npt_fcfinrea_b", "name" => "npt_fcfinrea_b");
$dalTablenptre["npt_estado_b"] = array("type"=>200,"varname"=>"npt_estado_b", "name" => "npt_estado_b");
$dalTablenptre["npt_cmplrq_b"] = array("type"=>200,"varname"=>"npt_cmplrq_b", "name" => "npt_cmplrq_b");
$dalTablenptre["npt_etnoveda_b"] = array("type"=>200,"varname"=>"npt_etnoveda_b", "name" => "npt_etnoveda_b");
$dalTablenptre["npt_fculting_b"] = array("type"=>7,"varname"=>"npt_fculting_b", "name" => "npt_fculting_b");
$dalTablenptre["npt_fcultret_b"] = array("type"=>7,"varname"=>"npt_fcultret_b", "name" => "npt_fcultret_b");
$dalTablenptre["npt_amnmi_b"] = array("type"=>3,"varname"=>"npt_amnmi_b", "name" => "npt_amnmi_b");
$dalTablenptre["npt_eraetfun_b"] = array("type"=>200,"varname"=>"npt_eraetfun_b", "name" => "npt_eraetfun_b");
$dalTablenptre["npt_eracdregdpn_b"] = array("type"=>200,"varname"=>"npt_eracdregdpn_b", "name" => "npt_eracdregdpn_b");
$dalTablenptre["npt_erarocoddpn_b"] = array("type"=>200,"varname"=>"npt_erarocoddpn_b", "name" => "npt_erarocoddpn_b");
$dalTablenptre["npt_eracargo_b"] = array("type"=>200,"varname"=>"npt_eracargo_b", "name" => "npt_eracargo_b");
$dalTablenptre["npt_eracoplz_b"] = array("type"=>3,"varname"=>"npt_eracoplz_b", "name" => "npt_eracoplz_b");
$dalTablenptre["npt_vrsdo_b"] = array("type"=>14,"varname"=>"npt_vrsdo_b", "name" => "npt_vrsdo_b");
$dalTablenptre["npt_vrgtorep_b"] = array("type"=>14,"varname"=>"npt_vrgtorep_b", "name" => "npt_vrgtorep_b");
$dalTablenptre["npt_vrpritec_b"] = array("type"=>14,"varname"=>"npt_vrpritec_b", "name" => "npt_vrpritec_b");
$dalTablenptre["npt_vrpricap_b"] = array("type"=>14,"varname"=>"npt_vrpricap_b", "name" => "npt_vrpricap_b");
$dalTablenptre["npt_vrpridir_b"] = array("type"=>14,"varname"=>"npt_vrpridir_b", "name" => "npt_vrpridir_b");
$dalTablenptre["npt_vrpriasc_b"] = array("type"=>14,"varname"=>"npt_vrpriasc_b", "name" => "npt_vrpriasc_b");
$dalTablenptre["npt_vrpriesp_b"] = array("type"=>14,"varname"=>"npt_vrpriesp_b", "name" => "npt_vrpriesp_b");
$dalTablenptre["npt_vrauxtra_b"] = array("type"=>14,"varname"=>"npt_vrauxtra_b", "name" => "npt_vrauxtra_b");
$dalTablenptre["npt_vrsubesp_b"] = array("type"=>14,"varname"=>"npt_vrsubesp_b", "name" => "npt_vrsubesp_b");
$dalTablenptre["npt_vrauxali_b"] = array("type"=>14,"varname"=>"npt_vrauxali_b", "name" => "npt_vrauxali_b");
$dalTablenptre["npt_vritvvd_b"] = array("type"=>14,"varname"=>"npt_vritvvd_b", "name" => "npt_vritvvd_b");
$dalTablenptre["npt_vrddcivv_b"] = array("type"=>14,"varname"=>"npt_vrddcivv_b", "name" => "npt_vrddcivv_b");
$dalTablenptre["npt_vrpigces_b"] = array("type"=>14,"varname"=>"npt_vrpigces_b", "name" => "npt_vrpigces_b");
$dalTablenptre["npt_esingres_b"] = array("type"=>200,"varname"=>"npt_esingres_b", "name" => "npt_esingres_b");
$dalTablenptre["npt_afsalari_b"] = array("type"=>200,"varname"=>"npt_afsalari_b", "name" => "npt_afsalari_b");
$dalTablenptre["npt_afcargo_b"] = array("type"=>200,"varname"=>"npt_afcargo_b", "name" => "npt_afcargo_b");
$dalTablenptre["npt_tpvinfun_b"] = array("type"=>200,"varname"=>"npt_tpvinfun_b", "name" => "npt_tpvinfun_b");
$dalTablenptre["npt_seraetfun_b"] = array("type"=>200,"varname"=>"npt_seraetfun_b", "name" => "npt_seraetfun_b");
$dalTablenptre["npt_afplanta_b"] = array("type"=>200,"varname"=>"npt_afplanta_b", "name" => "npt_afplanta_b");
$dalTablenptre["npt_esretiro_b"] = array("type"=>200,"varname"=>"npt_esretiro_b", "name" => "npt_esretiro_b");
$dalTablenptre["npt_fcnov_b"] = array("type"=>7,"varname"=>"npt_fcnov_b", "name" => "npt_fcnov_b");
$dalTablenptre["npt_tipo_b"] = array("type"=>200,"varname"=>"npt_tipo_b", "name" => "npt_tipo_b");
$dalTablenptre["npt_concepto_b"] = array("type"=>3,"varname"=>"npt_concepto_b", "name" => "npt_concepto_b");
$dalTablenptre["npt_nrnovref_b"] = array("type"=>14,"varname"=>"npt_nrnovref_b", "name" => "npt_nrnovref_b");
$dalTablenptre["npt_fcnovref_b"] = array("type"=>7,"varname"=>"npt_fcnovref_b", "name" => "npt_fcnovref_b");
$dalTablenptre["npt_prsobsue_b"] = array("type"=>14,"varname"=>"npt_prsobsue_b", "name" => "npt_prsobsue_b");
$dalTablenptre["npt_vrasiadi_b"] = array("type"=>14,"varname"=>"npt_vrasiadi_b", "name" => "npt_vrasiadi_b");
$dalTablenptre["npt_vraumaut_b"] = array("type"=>14,"varname"=>"npt_vraumaut_b", "name" => "npt_vraumaut_b");
$dalTablenptre["npt_vrpriloc_b"] = array("type"=>14,"varname"=>"npt_vrpriloc_b", "name" => "npt_vrpriloc_b");
$dalTablenptre["npt_vrprisal_b"] = array("type"=>14,"varname"=>"npt_vrprisal_b", "name" => "npt_vrprisal_b");
$dalTablenptre["npt_vrpritra_b"] = array("type"=>14,"varname"=>"npt_vrpritra_b", "name" => "npt_vrpritra_b");
$dalTablenptre["npt_vrdummy1_b"] = array("type"=>14,"varname"=>"npt_vrdummy1_b", "name" => "npt_vrdummy1_b");
$dalTablenptre["npt_vrdummy2_b"] = array("type"=>14,"varname"=>"npt_vrdummy2_b", "name" => "npt_vrdummy2_b");
$dalTablenptre["npt_vrdummy3_b"] = array("type"=>14,"varname"=>"npt_vrdummy3_b", "name" => "npt_vrdummy3_b");
$dalTablenptre["npt_fecha_b"] = array("type"=>7,"varname"=>"npt_fecha_b", "name" => "npt_fecha_b");
$dalTablenptre["npt_hora_b"] = array("type"=>200,"varname"=>"npt_hora_b", "name" => "npt_hora_b");
$dalTablenptre["npt_fcnscont_b"] = array("type"=>7,"varname"=>"npt_fcnscont_b", "name" => "npt_fcnscont_b");
$dalTablenptre["npt_referen_b"] = array("type"=>200,"varname"=>"npt_referen_b", "name" => "npt_referen_b");
$dalTablenptre["npt_tpdiasdur_b"] = array("type"=>200,"varname"=>"npt_tpdiasdur_b", "name" => "npt_tpdiasdur_b");
$dalTablenptre["npt_nrdiasdur_b"] = array("type"=>3,"varname"=>"npt_nrdiasdur_b", "name" => "npt_nrdiasdur_b");
	$dalTablenptre["npt_nrced_b"]["key"]=true;
	$dalTablenptre["npt_tpnpt_b"]["key"]=true;
	$dalTablenptre["npt_fcini_b"]["key"]=true;

$dal_info["edl_at_127_0_0_1__nptre"] = &$dalTablenptre;
?>