<?php
$dalTablesecop = array();
$dalTablesecop["secop_id"] = array("type"=>3,"varname"=>"secop_id", "name" => "secop_id");
$dalTablesecop["secop.nombre_entidad"] = array("type"=>200,"varname"=>"secop_nombre_entidad", "name" => "secop.nombre_entidad");
$dalTablesecop["secop.nit_entidad"] = array("type"=>200,"varname"=>"secop_nit_entidad", "name" => "secop.nit_entidad");
$dalTablesecop["secop.departamento"] = array("type"=>200,"varname"=>"secop_departamento", "name" => "secop.departamento");
$dalTablesecop["secop.ciudad"] = array("type"=>200,"varname"=>"secop_ciudad", "name" => "secop.ciudad");
$dalTablesecop["secop.localizaci_n"] = array("type"=>200,"varname"=>"secop_localizaci_n", "name" => "secop.localizaci_n");
$dalTablesecop["secop.orden"] = array("type"=>200,"varname"=>"secop_orden", "name" => "secop.orden");
$dalTablesecop["secop.sector"] = array("type"=>200,"varname"=>"secop_sector", "name" => "secop.sector");
$dalTablesecop["secop.rama"] = array("type"=>200,"varname"=>"secop_rama", "name" => "secop.rama");
$dalTablesecop["secop.entidad_centralizada"] = array("type"=>200,"varname"=>"secop_entidad_centralizada", "name" => "secop.entidad_centralizada");
$dalTablesecop["secop.proceso_de_compra"] = array("type"=>200,"varname"=>"secop_proceso_de_compra", "name" => "secop.proceso_de_compra");
$dalTablesecop["secop.id_contrato"] = array("type"=>200,"varname"=>"secop_id_contrato", "name" => "secop.id_contrato");
$dalTablesecop["secop.referencia_del_contrato"] = array("type"=>200,"varname"=>"secop_referencia_del_contrato", "name" => "secop.referencia_del_contrato");
$dalTablesecop["secop.estado_contrato"] = array("type"=>200,"varname"=>"secop_estado_contrato", "name" => "secop.estado_contrato");
$dalTablesecop["secop.codigo_de_categoria_principal"] = array("type"=>200,"varname"=>"secop_codigo_de_categoria_principal", "name" => "secop.codigo_de_categoria_principal");
$dalTablesecop["secop.descripcion_del_proceso"] = array("type"=>200,"varname"=>"secop_descripcion_del_proceso", "name" => "secop.descripcion_del_proceso");
$dalTablesecop["secop.tipo_de_contrato"] = array("type"=>200,"varname"=>"secop_tipo_de_contrato", "name" => "secop.tipo_de_contrato");
$dalTablesecop["secop.modalidad_de_contratacion"] = array("type"=>200,"varname"=>"secop_modalidad_de_contratacion", "name" => "secop.modalidad_de_contratacion");
$dalTablesecop["secop.justificacion_modalidad_de"] = array("type"=>200,"varname"=>"secop_justificacion_modalidad_de", "name" => "secop.justificacion_modalidad_de");
$dalTablesecop["secop.fecha_de_firma"] = array("type"=>200,"varname"=>"secop_fecha_de_firma", "name" => "secop.fecha_de_firma");
$dalTablesecop["secop.fecha_de_inicio_del_contrato"] = array("type"=>7,"varname"=>"secop_fecha_de_inicio_del_contrato", "name" => "secop.fecha_de_inicio_del_contrato");
$dalTablesecop["secop.fecha_de_fin_del_contrato"] = array("type"=>7,"varname"=>"secop_fecha_de_fin_del_contrato", "name" => "secop.fecha_de_fin_del_contrato");
$dalTablesecop["secop.fecha_de_inicio_de_ejecucion"] = array("type"=>200,"varname"=>"secop_fecha_de_inicio_de_ejecucion", "name" => "secop.fecha_de_inicio_de_ejecucion");
$dalTablesecop["secop.fecha_de_fin_de_ejecucion"] = array("type"=>200,"varname"=>"secop_fecha_de_fin_de_ejecucion", "name" => "secop.fecha_de_fin_de_ejecucion");
$dalTablesecop["secop.condiciones_de_entrega"] = array("type"=>200,"varname"=>"secop_condiciones_de_entrega", "name" => "secop.condiciones_de_entrega");
$dalTablesecop["secop.tipodocproveedor"] = array("type"=>200,"varname"=>"secop_tipodocproveedor", "name" => "secop.tipodocproveedor");
$dalTablesecop["secop.documento_proveedor"] = array("type"=>200,"varname"=>"secop_documento_proveedor", "name" => "secop.documento_proveedor");
$dalTablesecop["secop.proveedor_adjudicado"] = array("type"=>200,"varname"=>"secop_proveedor_adjudicado", "name" => "secop.proveedor_adjudicado");
$dalTablesecop["secop.es_grupo"] = array("type"=>200,"varname"=>"secop_es_grupo", "name" => "secop.es_grupo");
$dalTablesecop["secop.es_pyme"] = array("type"=>200,"varname"=>"secop_es_pyme", "name" => "secop.es_pyme");
$dalTablesecop["secop.habilita_pago_adelantado"] = array("type"=>200,"varname"=>"secop_habilita_pago_adelantado", "name" => "secop.habilita_pago_adelantado");
$dalTablesecop["secop.liquidaci_n"] = array("type"=>200,"varname"=>"secop_liquidaci_n", "name" => "secop.liquidaci_n");
$dalTablesecop["secop.obligaci_n_ambiental"] = array("type"=>200,"varname"=>"secop_obligaci_n_ambiental", "name" => "secop.obligaci_n_ambiental");
$dalTablesecop["secop.obligaciones_postconsumo"] = array("type"=>200,"varname"=>"secop_obligaciones_postconsumo", "name" => "secop.obligaciones_postconsumo");
$dalTablesecop["secop.reversion"] = array("type"=>200,"varname"=>"secop_reversion", "name" => "secop.reversion");
$dalTablesecop["secop.valor_del_contrato"] = array("type"=>200,"varname"=>"secop_valor_del_contrato", "name" => "secop.valor_del_contrato");
$dalTablesecop["secop.valor_de_pago_adelantado"] = array("type"=>200,"varname"=>"secop_valor_de_pago_adelantado", "name" => "secop.valor_de_pago_adelantado");
$dalTablesecop["secop.valor_facturado"] = array("type"=>200,"varname"=>"secop_valor_facturado", "name" => "secop.valor_facturado");
$dalTablesecop["secop.valor_pendiente_de_pago"] = array("type"=>200,"varname"=>"secop_valor_pendiente_de_pago", "name" => "secop.valor_pendiente_de_pago");
$dalTablesecop["secop.valor_pagado"] = array("type"=>200,"varname"=>"secop_valor_pagado", "name" => "secop.valor_pagado");
$dalTablesecop["secop.valor_amortizado"] = array("type"=>200,"varname"=>"secop_valor_amortizado", "name" => "secop.valor_amortizado");
$dalTablesecop["secop.valor_pendiente_de"] = array("type"=>200,"varname"=>"secop_valor_pendiente_de", "name" => "secop.valor_pendiente_de");
$dalTablesecop["secop.valor_pendiente_de_ejecucion"] = array("type"=>200,"varname"=>"secop_valor_pendiente_de_ejecucion", "name" => "secop.valor_pendiente_de_ejecucion");
$dalTablesecop["secop.estado_bpin"] = array("type"=>200,"varname"=>"secop_estado_bpin", "name" => "secop.estado_bpin");
$dalTablesecop["secop.c_digo_bpin"] = array("type"=>200,"varname"=>"secop_c_digo_bpin", "name" => "secop.c_digo_bpin");
$dalTablesecop["secop.anno_bpin"] = array("type"=>200,"varname"=>"secop_anno_bpin", "name" => "secop.anno_bpin");
$dalTablesecop["secop.saldo_cdp"] = array("type"=>200,"varname"=>"secop_saldo_cdp", "name" => "secop.saldo_cdp");
$dalTablesecop["secop.saldo_vigencia"] = array("type"=>200,"varname"=>"secop_saldo_vigencia", "name" => "secop.saldo_vigencia");
$dalTablesecop["secop.espostconflicto"] = array("type"=>200,"varname"=>"secop_espostconflicto", "name" => "secop.espostconflicto");
$dalTablesecop["secop.urlproceso.url"] = array("type"=>200,"varname"=>"secop_urlproceso_url", "name" => "secop.urlproceso.url");
$dalTablesecop["secop.destino_gasto"] = array("type"=>200,"varname"=>"secop_destino_gasto", "name" => "secop.destino_gasto");
$dalTablesecop["secop.origen_de_los_recursos"] = array("type"=>200,"varname"=>"secop_origen_de_los_recursos", "name" => "secop.origen_de_los_recursos");
$dalTablesecop["secop.d_as_adicionados"] = array("type"=>200,"varname"=>"secop_d_as_adicionados", "name" => "secop.d_as_adicionados");
$dalTablesecop["secop.puntos_del_acuerdo"] = array("type"=>200,"varname"=>"secop_puntos_del_acuerdo", "name" => "secop.puntos_del_acuerdo");
$dalTablesecop["secop.pilares_del_acuerdo"] = array("type"=>200,"varname"=>"secop_pilares_del_acuerdo", "name" => "secop.pilares_del_acuerdo");
	$dalTablesecop["secop_id"]["key"]=true;

$dal_info["sep2_at_127_0_0_1__secop"] = &$dalTablesecop;
?>