<?php
$dalTableep_op = array();
$dalTableep_op["OP_ID"] = array("type"=>3,"varname"=>"OP_ID", "name" => "OP_ID");
$dalTableep_op["Numero Documento"] = array("type"=>200,"varname"=>"Numero_Documento", "name" => "Numero Documento");
$dalTableep_op["Fecha de Registro"] = array("type"=>7,"varname"=>"Fecha_de_Registro", "name" => "Fecha de Registro");
$dalTableep_op["Fecha de pago"] = array("type"=>135,"varname"=>"Fecha_de_pago", "name" => "Fecha de pago");
$dalTableep_op["Estado"] = array("type"=>200,"varname"=>"Estado", "name" => "Estado");
$dalTableep_op["Valor Bruto"] = array("type"=>14,"varname"=>"Valor_Bruto", "name" => "Valor Bruto");
$dalTableep_op["Valor Deducciones"] = array("type"=>14,"varname"=>"Valor_Deducciones", "name" => "Valor Deducciones");
$dalTableep_op["Valor Neto"] = array("type"=>14,"varname"=>"Valor_Neto", "name" => "Valor Neto");
$dalTableep_op["Tipo Beneficiario"] = array("type"=>200,"varname"=>"Tipo_Beneficiario", "name" => "Tipo Beneficiario");
$dalTableep_op["Vigencia Presupuestal"] = array("type"=>200,"varname"=>"Vigencia_Presupuestal", "name" => "Vigencia Presupuestal");
$dalTableep_op["Tipo Identificacion"] = array("type"=>200,"varname"=>"Tipo_Identificacion", "name" => "Tipo Identificacion");
$dalTableep_op["Identificacion"] = array("type"=>200,"varname"=>"Identificacion", "name" => "Identificacion");
$dalTableep_op["Nombre Razon Social"] = array("type"=>200,"varname"=>"Nombre_Razon_Social", "name" => "Nombre Razon Social");
$dalTableep_op["Medio de Pago"] = array("type"=>200,"varname"=>"Medio_de_Pago", "name" => "Medio de Pago");
$dalTableep_op["Tipo Cuenta"] = array("type"=>200,"varname"=>"Tipo_Cuenta", "name" => "Tipo Cuenta");
$dalTableep_op["Numero Cuenta"] = array("type"=>200,"varname"=>"Numero_Cuenta", "name" => "Numero Cuenta");
$dalTableep_op["Estado Cuenta"] = array("type"=>200,"varname"=>"Estado_Cuenta", "name" => "Estado Cuenta");
$dalTableep_op["Entidad Nit"] = array("type"=>200,"varname"=>"Entidad_Nit", "name" => "Entidad Nit");
$dalTableep_op["Entidad Descripcion"] = array("type"=>200,"varname"=>"Entidad_Descripcion", "name" => "Entidad Descripcion");
$dalTableep_op["Dependencia"] = array("type"=>200,"varname"=>"Dependencia", "name" => "Dependencia");
$dalTableep_op["Dependencia Descripcion"] = array("type"=>200,"varname"=>"Dependencia_Descripcion", "name" => "Dependencia Descripcion");
$dalTableep_op["Rubro"] = array("type"=>200,"varname"=>"Rubro", "name" => "Rubro");
$dalTableep_op["Descripcion"] = array("type"=>200,"varname"=>"Descripcion", "name" => "Descripcion");
$dalTableep_op["Fuente"] = array("type"=>200,"varname"=>"Fuente", "name" => "Fuente");
$dalTableep_op["Recurso"] = array("type"=>200,"varname"=>"Recurso", "name" => "Recurso");
$dalTableep_op["Sit"] = array("type"=>200,"varname"=>"Sit", "name" => "Sit");
$dalTableep_op["Valor Pesos"] = array("type"=>14,"varname"=>"Valor_Pesos", "name" => "Valor Pesos");
$dalTableep_op["Valor Moneda"] = array("type"=>14,"varname"=>"Valor_Moneda", "name" => "Valor Moneda");
$dalTableep_op["Valor Reintegrado Pesos"] = array("type"=>14,"varname"=>"Valor_Reintegrado_Pesos", "name" => "Valor Reintegrado Pesos");
$dalTableep_op["Valor Reintegrado Moneda"] = array("type"=>14,"varname"=>"Valor_Reintegrado_Moneda", "name" => "Valor Reintegrado Moneda");
$dalTableep_op["Tesoreria Pagadora"] = array("type"=>200,"varname"=>"Tesoreria_Pagadora", "name" => "Tesoreria Pagadora");
$dalTableep_op["Identificacion Pagaduria"] = array("type"=>200,"varname"=>"Identificacion_Pagaduria", "name" => "Identificacion Pagaduria");
$dalTableep_op["Cuenta Pagaduria"] = array("type"=>200,"varname"=>"Cuenta_Pagaduria", "name" => "Cuenta Pagaduria");
$dalTableep_op["Endosada"] = array("type"=>200,"varname"=>"Endosada", "name" => "Endosada");
$dalTableep_op["Tipo Identificacion1"] = array("type"=>200,"varname"=>"Tipo_Identificacion1", "name" => "Tipo Identificacion1");
$dalTableep_op["Identificacion1"] = array("type"=>200,"varname"=>"Identificacion1", "name" => "Identificacion1");
$dalTableep_op["Razon social"] = array("type"=>200,"varname"=>"Razon_social", "name" => "Razon social");
$dalTableep_op["Numero Cuenta1"] = array("type"=>200,"varname"=>"Numero_Cuenta1", "name" => "Numero Cuenta1");
$dalTableep_op["Concepto Pago"] = array("type"=>200,"varname"=>"Concepto_Pago", "name" => "Concepto Pago");
$dalTableep_op["Solicitud CDP"] = array("type"=>200,"varname"=>"Solicitud_CDP", "name" => "Solicitud CDP");
$dalTableep_op["CDP"] = array("type"=>200,"varname"=>"CDP", "name" => "CDP");
$dalTableep_op["Compromisos"] = array("type"=>200,"varname"=>"Compromisos", "name" => "Compromisos");
$dalTableep_op["Cuentas por Pagar"] = array("type"=>200,"varname"=>"Cuentas_por_Pagar", "name" => "Cuentas por Pagar");
$dalTableep_op["Fecha Cuentas por Pagar"] = array("type"=>200,"varname"=>"Fecha_Cuentas_por_Pagar", "name" => "Fecha Cuentas por Pagar");
$dalTableep_op["Obligaciones"] = array("type"=>200,"varname"=>"Obligaciones", "name" => "Obligaciones");
$dalTableep_op["Ordenes de Pago"] = array("type"=>200,"varname"=>"Ordenes_de_Pago", "name" => "Ordenes de Pago");
$dalTableep_op["Reintegros"] = array("type"=>200,"varname"=>"Reintegros", "name" => "Reintegros");
$dalTableep_op["Fecha Doc Soporte Compromiso"] = array("type"=>200,"varname"=>"Fecha_Doc_Soporte_Compromiso", "name" => "Fecha Doc Soporte Compromiso");
$dalTableep_op["Tipo Doc Soporte Compromiso"] = array("type"=>200,"varname"=>"Tipo_Doc_Soporte_Compromiso", "name" => "Tipo Doc Soporte Compromiso");
$dalTableep_op["Num Doc Soporte Compromiso"] = array("type"=>200,"varname"=>"Num_Doc_Soporte_Compromiso", "name" => "Num Doc Soporte Compromiso");
$dalTableep_op["Objeto del Compromiso"] = array("type"=>200,"varname"=>"Objeto_del_Compromiso", "name" => "Objeto del Compromiso");
	$dalTableep_op["OP_ID"]["key"]=true;

$dal_info["sep2_at_127_0_0_1__ep_op"] = &$dalTableep_op;
?>