<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_ep_op_temp  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeImport"]=true;

		$this->events["AfterImport"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before Import Started
function BeforeImport(&$pageObject, &$message)
{

		$sql = DB::prepareSQL("TRUNCATE TABLE sep2.ep_op_temp;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeImport

		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After Import Finished
function AfterImport($count, $skipCount, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.ep_op_temp
SET
sep2.ep_op_temp.`Valor Bruto` = REPLACE(sep2.ep_op_temp.`Valor Bruto`,',',''),
sep2.ep_op_temp.`Valor Deducciones` = REPLACE(sep2.ep_op_temp.`Valor Deducciones`,',',''),
sep2.ep_op_temp.`Valor Neto` = REPLACE(sep2.ep_op_temp.`Valor Neto`,',',''),
sep2.ep_op_temp.`Valor Pesos`= REPLACE(sep2.ep_op_temp.`Valor Pesos`,',',''),
sep2.ep_op_temp.`Valor Moneda` = REPLACE(sep2.ep_op_temp.`Valor Moneda`,',',''),
sep2.ep_op_temp.`Valor Reintegrado Pesos` = REPLACE(sep2.ep_op_temp.`Valor Reintegrado Pesos`,',',''),
sep2.ep_op_temp.`Valor Reintegrado Moneda` = REPLACE(sep2.ep_op_temp.`Valor Reintegrado Moneda`,',','');");
DB::Exec( $sql );

$sql = DB::prepareSQL("INSERT IGNORE INTO sep2.ep_op (
	sep2.ep_op.`Numero Documento`,
	sep2.ep_op.`Fecha de Registro`,
	sep2.ep_op.`Fecha de pago`,
	sep2.ep_op.Estado,
	sep2.ep_op.`Valor Bruto`,
	sep2.ep_op.`Valor Deducciones`,
	sep2.ep_op.`Valor Neto`,
	sep2.ep_op.`Tipo Beneficiario`,
	sep2.ep_op.`Vigencia Presupuestal`,
	sep2.ep_op.`Tipo Identificacion`,
	sep2.ep_op.Identificacion,
	sep2.ep_op.`Nombre Razon Social`,
	sep2.ep_op.`Medio de Pago`,
	sep2.ep_op.`Tipo Cuenta`,
	sep2.ep_op.`Numero Cuenta`,
	sep2.ep_op.`Estado Cuenta`,
	sep2.ep_op.`Entidad Nit`,
	sep2.ep_op.`Entidad Descripcion`,
	sep2.ep_op.Dependencia,
	sep2.ep_op.`Dependencia Descripcion`,
	sep2.ep_op.Rubro,
	sep2.ep_op.Descripcion,
	sep2.ep_op.Fuente,
	sep2.ep_op.Recurso,
	sep2.ep_op.Sit,
	sep2.ep_op.`Valor Pesos`,
	sep2.ep_op.`Valor Moneda`,
	sep2.ep_op.`Valor Reintegrado Pesos`,
	sep2.ep_op.`Valor Reintegrado Moneda`,
	sep2.ep_op.`Tesoreria Pagadora`,
	sep2.ep_op.`Identificacion Pagaduria`,
	sep2.ep_op.`Cuenta Pagaduria`,
	sep2.ep_op.Endosada,
	sep2.ep_op.`Tipo Identificacion1`,
	sep2.ep_op.Identificacion1,
	sep2.ep_op.`Razon social`,
	sep2.ep_op.`Numero Cuenta1`,
	sep2.ep_op.`Concepto Pago`,
	sep2.ep_op.`Solicitud CDP`,
	sep2.ep_op.CDP,
	sep2.ep_op.Compromisos,
	sep2.ep_op.`Cuentas por Pagar`,
	sep2.ep_op.`Fecha Cuentas por Pagar`,
	sep2.ep_op.Obligaciones,
	sep2.ep_op.`Ordenes de Pago`,
	sep2.ep_op.Reintegros,
	sep2.ep_op.`Fecha Doc Soporte Compromiso`,
	sep2.ep_op.`Tipo Doc Soporte Compromiso`,
	sep2.ep_op.`Num Doc Soporte Compromiso`,
	sep2.ep_op.`Objeto del Compromiso`
) SELECT
sep2.ep_op_temp.`Numero Documento`,
sep2.ep_op_temp.`Fecha de Registro`,
sep2.ep_op_temp.`Fecha de pago`,
sep2.ep_op_temp.Estado,
sep2.ep_op_temp.`Valor Bruto`,
sep2.ep_op_temp.`Valor Deducciones`,
sep2.ep_op_temp.`Valor Neto`,
sep2.ep_op_temp.`Tipo Beneficiario`,
sep2.ep_op_temp.`Vigencia Presupuestal`,
sep2.ep_op_temp.`Tipo Identificacion`,
sep2.ep_op_temp.Identificacion,
sep2.ep_op_temp.`Nombre Razon Social`,
sep2.ep_op_temp.`Medio de Pago`,
sep2.ep_op_temp.`Tipo Cuenta`,
sep2.ep_op_temp.`Numero Cuenta`,
sep2.ep_op_temp.`Estado Cuenta`,
sep2.ep_op_temp.`Entidad Nit`,
sep2.ep_op_temp.`Entidad Descripcion`,
sep2.ep_op_temp.Dependencia,
sep2.ep_op_temp.`Dependencia Descripcion`,
sep2.ep_op_temp.Rubro,
sep2.ep_op_temp.Descripcion,
sep2.ep_op_temp.Fuente,
sep2.ep_op_temp.Recurso,
sep2.ep_op_temp.Sit,
sep2.ep_op_temp.`Valor Pesos`,
sep2.ep_op_temp.`Valor Moneda`,
sep2.ep_op_temp.`Valor Reintegrado Pesos`,
sep2.ep_op_temp.`Valor Reintegrado Moneda`,
sep2.ep_op_temp.`Tesoreria Pagadora`,
sep2.ep_op_temp.`Identificacion Pagaduria`,
sep2.ep_op_temp.`Cuenta Pagaduria`,
sep2.ep_op_temp.Endosada,
sep2.ep_op_temp.`Tipo Identificacion1`,
sep2.ep_op_temp.Identificacion1,
sep2.ep_op_temp.`Razon social`,
sep2.ep_op_temp.`Numero Cuenta1`,
sep2.ep_op_temp.`Concepto Pago`,
sep2.ep_op_temp.`Solicitud CDP`,
sep2.ep_op_temp.CDP,
sep2.ep_op_temp.Compromisos,
sep2.ep_op_temp.`Cuentas por Pagar`,
sep2.ep_op_temp.`Fecha Cuentas por Pagar`,
sep2.ep_op_temp.Obligaciones,
sep2.ep_op_temp.`Ordenes de Pago`,
sep2.ep_op_temp.Reintegros,
sep2.ep_op_temp.`Fecha Doc Soporte Compromiso`,
sep2.ep_op_temp.`Tipo Doc Soporte Compromiso`,
sep2.ep_op_temp.`Num Doc Soporte Compromiso`,
sep2.ep_op_temp.`Objeto del Compromiso`
FROM sep2.ep_op_temp;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterImport

		
		
		
		



}
?>
