<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_hoja_ruta_2020_pn2  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("INSERT INTO dbct.hoja_ruta_2020_tracking (
	dbct.hoja_ruta_2020_tracking.hr_id_fk,
	dbct.hoja_ruta_2020_tracking.hr_asunto,
	dbct.hoja_ruta_2020_tracking.sys_user,
	dbct.hoja_ruta_2020_tracking.hr_valor,
	dbct.hoja_ruta_2020_tracking.hr_fechaingreso,
	dbct.hoja_ruta_2020_tracking.not_user,
	dbct.hoja_ruta_2020_tracking.not_date,
	dbct.hoja_ruta_2020_tracking.not_mail,
	dbct.hoja_ruta_2020_tracking.not_msg,
	dbct.hoja_ruta_2020_tracking.evento_type_id_fk,
dbct.hoja_ruta_2020_tracking.user_from,
dbct.hoja_ruta_2020_tracking.last_act_user
) SELECT
dbct.hoja_ruta_2020.hr_id,
dbct.hoja_ruta_2020.hr_asunto,
dbct.hoja_ruta_2020.sys_user,
dbct.hoja_ruta_2020.hr_valor,
dbct.hoja_ruta_2020.hr_fechaingreso,
dbct.hoja_ruta_2020.not_user,
dbct.hoja_ruta_2020.not_date,
dbct.hoja_ruta_2020.not_mail,
dbct.hoja_ruta_2020.not_msg,
dbct.hoja_ruta_2020.evento_type_id_fk,
dbct.hoja_ruta_2020.user_from,
dbct.hoja_ruta_2020.last_act_user
FROM
	dbct.hoja_ruta_2020  
WHERE dbct.hoja_ruta_2020.hr_id =".$keys['hr_id']);
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
dbct.hoja_ruta_2020
SET
dbct.hoja_ruta_2020.anio = YEAR(dbct.hoja_ruta_2020.hr_fechaingreso),
dbct.hoja_ruta_2020.mes = MONTH(dbct.hoja_ruta_2020.hr_fechaingreso);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("INSERT INTO dbct.hoja_ruta_2020_tracking (
	dbct.hoja_ruta_2020_tracking.hr_id_fk,
	dbct.hoja_ruta_2020_tracking.hr_asunto,
	dbct.hoja_ruta_2020_tracking.sys_user,
	dbct.hoja_ruta_2020_tracking.hr_valor,
	dbct.hoja_ruta_2020_tracking.hr_fechaingreso,
	dbct.hoja_ruta_2020_tracking.not_user,
	dbct.hoja_ruta_2020_tracking.not_date,
	dbct.hoja_ruta_2020_tracking.not_mail,
	dbct.hoja_ruta_2020_tracking.not_msg,
	dbct.hoja_ruta_2020_tracking.evento_type_id_fk,
dbct.hoja_ruta_2020_tracking.user_from,
dbct.hoja_ruta_2020_tracking.last_act_user
) SELECT
dbct.hoja_ruta_2020.hr_id,
dbct.hoja_ruta_2020.hr_asunto,
dbct.hoja_ruta_2020.sys_user,
dbct.hoja_ruta_2020.hr_valor,
dbct.hoja_ruta_2020.hr_fechaingreso,
dbct.hoja_ruta_2020.not_user,
dbct.hoja_ruta_2020.not_date,
dbct.hoja_ruta_2020.not_mail,
dbct.hoja_ruta_2020.not_msg,
dbct.hoja_ruta_2020.evento_type_id_fk,
dbct.hoja_ruta_2020.user_from,
dbct.hoja_ruta_2020.last_act_user
FROM
	dbct.hoja_ruta_2020  
WHERE dbct.hoja_ruta_2020.hr_id =".$keys['hr_id']);
DB::Exec( $sql );

//**********  Send email with new data  ************
if($values['evento_type_id_fk'] != 67){
$email=$values['not_mail'];
$from="notificacionsiseg@mindeporte.gov.co";
$fromName="SISEG | PAGOS ";
$msg="Se han registrado cambios en el Radicado No. ".$values['hr_id']." revisa tu bandeja de entrada"."\r\n";
$subject="Novedad en solicitud de pago | Persona Natural :: Radicado: ".$values['hr_id'];

$msg.= "Comentarios: ".$values['not_msg']."\r\n";
$msg.= "Hoja de ruta: ".$values['hr_id']."\r\n";
$msg.= "Asunto: ".$values['hr_asunto']."\r\n";
$msg.= "Para atender esta solicitud ingrese a: https://sisecg.mindeporte.gov.co/athena/GestionPagos/login.php"."\r\n";
//$msg.= "Age: ".$values["age"]."\r\n";

$ret=runner_mail(array('to' => $email, 'cc' => 'dito73@gmail.com', 'subject' => $subject, 'body' => $msg, 'fromName'=> $fromName, 'from'=>$from));
if(!$ret["mailed"])
	echo $ret["message"];
}
else
{
$email=$values['tercero_email_a'].",".$values['tercero_email_b'];
$from="notificacionsiseg@mindeporte.gov.co";
$fromName="SISEG | PAGOS ";
$msg="Se han registrado cambios en el Radicado No. ".$values['hr_id']." revisa tu bandeja de entrada"."\r\n";
$subject="Información sobre el pago | Persona Natural :: Radicado: ".$values['hr_id'];

$msg.= "Comentarios: ".$values['not_msg']."\r\n";
$msg.= "Hoja de ruta: ".$values['hr_id']."\r\n";
$msg.= "Asunto: ".$values['hr_asunto']."\r\n";
$msg.= "Para consultar información relacionada con esta solicitud ingrese a: https://sisecg.mindeporte.gov.co/athena/GestionContratistas/"."\r\n";
//$msg.= "Age: ".$values["age"]."\r\n";

$ret=runner_mail(array('to' => $email, 'cc' => 'info@catalogotecnologico.co', 'subject' => $subject, 'body' => $msg, 'fromName'=> $fromName, 'from'=>$from));
if(!$ret["mailed"])
	echo $ret["message"];
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
